### ISSUE TITLE
Dropdown enhancement 

### ISSUE THREAD

**Issue by KabluBR** [Semantic-Org/Semantic-UI#1000]
Hi,

I was using a lot dropdowns and I had a problem with the atual dropdown as its items (options) does not fit the same width of the parent, and in some cases it was a little buggy (depending on the size of the text) so I made this changes on css to fit the content inside the box...
I think you can implement it as "fitted" option of the original dropdown, like "ui fitted dropdown" or something like that.

Try this:

``` css
.ui.selection.dropdown {
    width: 100%;
    margin-top: 0.1em;
    height: 2.3em;
}

.ui.selection.dropdown .menu {
    width: 100%;
    white-space: normal !important;
}

.ui.selection.dropdown .menu .item:first-child {
    border-top: 1px solid #ddd !important;
    min-height: 2.8em;
}

.ui.selection.dropdown .text {
    overflow: hidden;
    text-overflow: ellipsis;
    white-space: nowrap;
    width: 90%;
}

.ui.selection.dropdown .icon {
    text-align: right;
    margin-left: 7px !important;
}
```

Well, this is what I did but I know you can do it better!

Thanks
