### ISSUE TITLE
Dropdown doesn't work in IE9

### ISSUE THREAD

**Issue by kodermax** [Semantic-Org/Semantic-UI#1185]
Dropdown doesn't work in IE9

**Comment by joshbodine21** [comment]
For what its worth, when the transition is complete it calls "module.event.resetStyle.call(this);" This removes the attribute style and is what causes the issue. Not removing the style allows IE 9 to work.

**Comment by smeijer** [comment]
For those who are interested, the IE9 fix for a dropdown is pretty simple.

Include a IE9-only css file, and add the folowing css rules:

```html
<head>
  <link href="/semantic-ui.css" rel="stylesheet" />
  <!--[if IE 9]>
    <link href="/ie9-fixes.css" rel="stylesheet" />
  <![endif]-->
</head>
```

```css
/* ie9-fixes.css */
.dropdown.item.ui.visible > .menu,
.dropdown.selection.ui.visible > .menu {
   display: block !important;
   visibility: visible !important;
}
```
