### ISSUE TITLE
[1.0] Text Color during animation of drop down in inverted menu not inverted

### ISSUE THREAD

**Issue by mzbyszynski** [Semantic-Org/Semantic-UI#1190]
See here: http://jsfiddle.net/x4c2d4z9/1/

When you select a different option, the color of the text displayed in the .ui.dropdown>.text element briefly changes from white (the color it should be in an inverted menu) to black.

I was able to fix this by adding the following css to my project:
```css
.ui.inverted.menu .ui.selection.dropdown.item>input.search,
.ui.inverted.menu .ui.selection.dropdown.item>input.search:focus,
.ui.inverted.menu .ui.selection.active.dropdown.item>.text:not(.default),
.ui.inverted.menu .ui.selection.visible.dropdown.item>.text:not(.default) {
  color: #fff;
}

.ui.inverted.menu .ui.selection.dropdown.item>input.search:focus + .text {
  color: rgba(255, 255, 255, 0.7) !important;
}
```

I am happy to submit a PR if that helps, but I wasn't sure if this belongs in menu.less or dropdown.less.

Usually you fix the bugs I find before I manage to submit them, so I'm glad I finally got one in :D
