### ISSUE TITLE
[1.0] Checkbox icon broken due to font src missing quotes

### ISSUE THREAD

**Issue by inDream** [Semantic-Org/Semantic-UI#1197]
I download version 1.0 with bower, and checked checkbox cannot display the checked icon.
Demo: http://jsfiddle.net/dz43d6q2/
The bug is due to compiled `semantic.css` dropped quotes(`url('data`->`url(data`) & words(`base64`->`base6`) in `src` property.

In `dist/components/checkbox.css`

``` css
@font-face {
  font-family: 'Checkbox';
  src: url('data:application/octet-stream;base64,...') format('woff'), url('data:application/octet-stream;base64,...') format('truetype');
}
```

In `dist/semantic.css`

``` css
@font-face {
  font-family: 'Checkbox';
  src: url(data:application/octet-stream;base6,...') format('woff'), url(data:application/octet-stream;base6,..') format('truetype');
}
```
