### ISSUE TITLE
[UI] Input Slider / Range Component

### ISSUE THREAD

**Issue by q-depot** [Semantic-Org/Semantic-UI#1336]
Hi,

does the UI comes with sliders? I couldn't find it anywhere in the website so I assume it doesn't, but I saw the buttons can be displayed as (toggle)sliders. That's not what I'm looking for but I thought there might be a widget somewhere.

Another note on the side, it would be cool to have a knob widget.

**Comment by sevki** [comment]
:+1:

**Comment by nicbarker** [comment]
Would love this feature, don't enjoy having to use the jquery UI component but it does the job at the moment.

**Comment by hrstoyanov** [comment]
jlukich,
Where is the documentation on the new Range component. I could not find it at beta.semantic-ui.com

Thanks for your hard work!

**Comment by jlukic** [comment]
There is not a new range component with 2.0. Not enough time.

**Comment by mjhasbach** [comment]
+1

**Comment by mrjonny2** [comment]
+1

**Comment by rachellji** [comment]
+1

**Comment by scotthasbrouck** [comment]
+1

**Comment by michahell** [comment]
+1

**Comment by pfhor** [comment]
+1

**Comment by avalanche1** [comment]
+1

**Comment by jeanlescure** [comment]
+1

**Comment by pulsingbrain** [comment]
+1

**Comment by Timonzimm** [comment]
+1

**Comment by jlukic** [comment]
I started working on this

**Comment by avalanche1** [comment]
Jack, please include:
- a vertical variation
- a way to add ticks with labels to slider axis

**Comment by jlukic** [comment]
I plan on supporting both of those cases.

**Comment by avalanche1** [comment]
Nice to have you back!)

**Comment by mrjonny2** [comment]
Any word on when this will be done? Sorry to rush 😄

**Comment by pashadia** [comment]
+1

**Comment by vakorovin** [comment]
+1

**Comment by lsunsi** [comment]
+1 Awesome work man (:

**Comment by namwkim** [comment]
+1

**Comment by miroslavbucek** [comment]
+1 thanks!

**Comment by David-Desmaisons** [comment]
+1

**Comment by kataras** [comment]
+1 Slider is useful, unfortunaly I am still using a plugin named 'bootstrap-slider', because I couldn't find any slider component for semantic ui and I am migrating all my sites from bootstrap to semantic ui.

**Comment by tyleryasaka** [comment]
Hey all, I put together a Semantic-inspired range slider module. The design is based off the Semantic UI slider-style checkbox input. It works for both mouse and touchscreen, can be disabled, and comes in all the Semantic UI colors and inverted colors. Seeing how many people are looking for this feature, maybe this will be useful to someone. Not sure where the team is at on implementing a range slider, but I'd be happy to contribute if I could be of help.
[Demo](http://codepen.io/tyleryasaka/pen/KVqPbo)
https://github.com/tyleryasaka/semantic-ui-range

**Comment by jeanlescure** [comment]
@tyleryasaka that's definitely what I was looking for in terms of look and feel, didn't see a way to set the _step_ amount, as in how much each step adds or removes to the value, I'd say that's the only missing functionality for it to match the native `<range>` element (http://www.html5tutorial.info/html5-range.php).

Cheers on a job well done :+1: , already starred it in case I need it in the future. I'd propose to the Semantic team to officially pull in this solution.

**Comment by tyleryasaka** [comment]
Thanks @jeanlescure . Per your suggestion I added the ability to set the step.

**Comment by jlukic** [comment]
@tyleryasaka Looks great :smile

**Comment by tyleryasaka** [comment]
@jlukic Glad you like it :blush:

**Comment by hoxxep** [comment]
Or, some simple styles to go on top of the HTML5 `range` input - no JS required. Basic demo: [http://codepen.io/anon/pen/xZYpGQ](http://codepen.io/anon/pen/xZYpGQ)

```html
<input class="ui range" type="range" name="demo" min="0" max="10" step="1">
```

```less
.ui.range {
  &input[type="range"] {
    width: 100%;
    -webkit-appearance: none;
    border: 1px solid #ddd;
    padding: 0;
    height: 0;
    margin-top: 1rem;
    margin-bottom: 1rem;
  }

  &input[type="range"]:focus {
    border-color: #ccc;
    outline: none !important;
  }

  &input[type="range"]::-moz-range-track {
    background: none;
    border: 0;
  }

  &input[type="range"]::-moz-focus-outer {
    border: 0;
  }

  &input[type="range"]::-webkit-slider-thumb {
    -webkit-appearance: none;
    height: 1.5rem;
    width: 1.5rem;

    background: #fff;
    background: #fff linear-gradient(transparent, rgba(0, 0, 0, 0.05));
    background: #fff -webkit-linear-gradient(transparent, rgba(0, 0, 0, 0.05));
    background: #fff -o-linear-gradient(transparent, rgba(0, 0, 0, 0.05));
    background: #fff -moz-linear-gradient(transparent, rgba(0, 0, 0, 0.05));
    border-radius: 100%;
    box-shadow: 0 1px 2px 0 rgba(34,36,38,.15),0 0 0 1px rgba(34,36,38,.15) inset;
  }

  &input[type="range"]::-moz-range-thumb {
    height: 1.5rem;
    width: 1.5rem;

    background: #fff;
    background: #fff linear-gradient(transparent, rgba(0, 0, 0, 0.05));
    background: #fff -webkit-linear-gradient(transparent, rgba(0, 0, 0, 0.05));
    background: #fff -o-linear-gradient(transparent, rgba(0, 0, 0, 0.05));
    background: #fff -moz-linear-gradient(transparent, rgba(0, 0, 0, 0.05));
    border-radius: 100%;
    box-shadow: 0 1px 2px 0 rgba(34,36,38,.15),0 0 0 1px rgba(34,36,38,.15) inset;
  }
}
```
