### ISSUE TITLE
[Dropdown] missing top border / pointing arrow on selection dropdown with wide menu content

### ISSUE THREAD

**Issue by larsbo** [Semantic-Org/Semantic-UI#1458]
I have a dropdown with wide menu content and found 2 issues related to this use case:

The top border of the menu that is wider than the parent dropdown element has no top border (see jsfiddle http://jsfiddle.net/dqtojuuu/ example 1).

So I tried the `.top.pointing` variant but it seems this doesn't work together with `.ui.dropdown.selection` because there is no top border at all and also no pointing arrow (see jsfiddle http://jsfiddle.net/dqtojuuu/ example 2).

**Comment by larsbo** [comment]
Thank you for the clear answer, @jlukic . I have to amit I didn't read the full documentation :frowning: 

I also understand your icon order hint after viewing the page in chrome ;-) (firefox shows the dropdown icon correctly also in the reverse order),

For the first issue (the long menu without top border) I made a small workaround that looks ok for me. If someone is interested here is the fiddle:
http://jsfiddle.net/99bqnywe/2/

or just the css:
```css
/* remove menu item word wrapping */
.ui.selection.dropdown .menu > .item {
    white-space: nowrap;
}

/* remove bottom border from dropdown */
.ui.selection.dropdown.visible:after {
	background-color: #fff;
	bottom: -1px;
	content: "";
	display: block;
	height: 2px;
	left: 0;
	position: absolute;
	width: 100%;
	z-index: 11;
}

/* add top border to dropdown menu */
.ui.selection.dropdown .menu {
	border-top: 1px solid rgba(39, 41, 43, 0.15) !important;
    border-top-right-radius: 0.2857rem;
}
.ui.selection.visible.dropdown:hover .menu {
	border-top-color: rgba(39, 41, 43, 0.3) !important;
}
```
