### ISSUE TITLE
Evenly Divided Button Rollover Display Bug

### ISSUE THREAD

**Issue by thinksaydo** [Semantic-Org/Semantic-UI#1483]
I'm using latest stable released Chrome. When I roll over the Evenly Divided Buttons on this page: http://semantic-ui.com/elements/button.html from left to right, the background color doesn't properly reset until moving the cursor completely off the button group.

Looks like removing the position: relative from this style would fix the issue:

```css
.ui.buttons>.button.active, .ui.buttons>.button:hover {
    position: relative;
}
```
