### ISSUE TITLE
Change global box-sizing to be more easily modified

### ISSUE THREAD

**Issue by ShimShamSam** [Semantic-Org/Semantic-UI#1535]
Instead of

``` CSS
*,
*:before,
*:after {
  box-sizing: border-box;
}
```

It's more flexible to use

``` CSS
*,
*:before,
*:after {
  box-sizing: inherit;
}

html {
  box-sizing: border-box;
}
```

This allows users to change the box-sizing on a parent element and have it cascade to its children. Legacy styles might rely on this. The only concern might be if this affects performance or not.
