### ISSUE TITLE
fix pusher element show

### ISSUE THREAD

**Issue by antonkulaga** [Semantic-Org/Semantic-UI#1674]
Sidebar in push_mode works in a different way then in 0.1.x versions of Semantic UI. 
In previous major version it did not make body wider then a screen but in current version I get constant overflow of body. I would like either to get back previous behavior or to have an option in settings that will make sidebar pushing behave in a way as in previous major version.

I think this effect can be achieved by something like:
```css
.ui.visible.left.sidebar ~ .pusher {
  margin-right: 260px; //as you use less probably there should be a variable
}
```
