### ISSUE TITLE
Double sidebar pusher transforms

### ISSUE THREAD

**Issue by drew-py** [Semantic-Org/Semantic-UI#1747]
Would it be possible to have a setting that allows the pusher div to stay constrained by the containing div's size when pushed, or at worst the page size. It could resize it's width and/or height as the sidebars come out instead of just transforming sideways? I have a use case where I'd like to have all pusher content remain visible but just resize in a fluid layout.
There are also some bugs that might possibly be caused by this design (or possibly something else that I missed).

With its current behavior you get some strange quirks as the interactions confuse it's state as it gets knocked about by sidebars opening and closing.

e.g. In a fork of the fiddle from this (https://github.com/Semantic-Org/Semantic-UI/issues/1745) issue you can see what I mean by clicking LEFT, then RIGHT, then clicking in the whitespace to close the sidebars then clicking RIGHT again.

http://jsfiddle.net/kv9r67ka/1/
edit: fixed fiddle.

**Comment by jlukic** [comment]
Nothing built in for attaching things to overlay sidebars. 

Can rig up in css by keeping your button on same level as visible sidebar and using sibling selector.

Something like
```css
.ui.visible.right.sidebar ~ #my-button {
-webkit-transform: translate3d(-260px, 0, 0);
transform: translate3d(-260px, 0, 0);
transition: 0.5s all;
}
```
