### ISSUE TITLE
Google penalty for mobile platforms font size

### ISSUE THREAD

**Issue by Enelar** [Semantic-Org/Semantic-UI#1808]
According to [Google](https://developers.google.com/speed/docs/insights/UseLegibleFontSizes), you should use base font size 16px or more(now 14px [semantic.css](https://github.com/Semantic-Org/Semantic-UI/blob/master/dist/semantic.css#L522)). And every other sizes should be relative to base(em,rem), for typographic scale.

I think we just can't ignore [Google Page Insights](https://developers.google.com/speed/pagespeed/insights/).
If you allow me, i will contribute it.

**Comment by jlukic** [comment]
Everything is based on `em` size in SUI, which follows all guidelines. Perhaps google says 16px is a good font size for mobile. But I still prefer 14. 

If you wanted to add for your project its fairly simple.
```less
@media only screen and (max-width: (@largestMobileScreen)) {
  html, body {
    font-size: 16px;
  }
}
```
