### ISSUE TITLE
Sidebar with custom element context does not remain fixed to window.

### ISSUE THREAD

**Issue by tastywheat** [Semantic-Org/Semantic-UI#1811]
When setting the context to another element, the sidebar does not remain fixed to the window.

In the following fiddle, open the sidebar, then scroll down: http://jsfiddle.net/xze5p388/1/

This seems to be related to Fixed positioned elements and css3 translate3d: http://stackoverflow.com/questions/15194313/webkit-css-transform3d-position-fixed-issue

Specifically, this style is causing the issue:

.pushable:not(body) {
  -webkit-transform: translate3d(0,0,0);
  transform: translate3d(0,0,0);
}

**Comment by jlukic** [comment]
A sidebars fixed position is designed to be attached to `context`. If you need to wrap your page in a div you can make sure `overflow` is on your div and not `html`.

```css
html, body {
  overflow: hidden;
}
.mywrapper {
  overflow: auto;
  -webkit-overflow-scrolling: touch;
}
```

The `transform: translate3d(0, 0, 0);` was intentional to trigger the sidebar attaching itself to context. This interaction has been reworked somewhat in `next` see #1771
