### ISSUE TITLE
Calculator icon is missing

### ISSUE THREAD

**Issue by ljubic** [Semantic-Org/Semantic-UI#1882]
I've downloaded the latest build from Semantic UI homepage. I wanted to use Calculator icon, but it's missing from semantic.css/icon.css files & from fonts I've downloaded with the project. I've solved the problem by adding following lines to css files & downloading old fonts loaded on [Icons](http://semantic-ui.com/elements/icon.html) demo page: 

```css
    i.icon.calculator:before {
        content: "\f1ec";
    }
```
Please note that Calculator icon is working on Icons demo page, but not in latest build which is available for download through Semantic UI website.
