### ISSUE TITLE
Adding colors to Toggle

### ISSUE THREAD

**Issue by piernik** [Semantic-Org/Semantic-UI#1883]
Now toggle button is always green - can You add ability to declare color? red, blue, teal?

**Comment by jlukic** [comment]
This is easy to change with theming, https://github.com/Semantic-Org/Semantic-UI/blob/master/src/themes/default/modules/checkbox.variables#L12 

We wont support multiple colors for checkbox, it doesn't fit in with my design sensibilities for checkbox ui.

**Comment by piernik** [comment]
I'll do it - no problem but I think it should be in core

**Comment by kamalkhan** [comment]
**A snippet to generate an infinite amount of colored checkboxes** (less)

```less
@colors: red, green, blue, violet, pink, black, white;
.ui.toggle.checkbox {
    .-(@i: length(@colors)) when (@i > 0) {
        @c: extract(@colors, @i);
        &.@{c} {
            input:checked~label {
                color: @c;
                &:before { background-color: @c; }
            }
        }
        .-((@i - 1));
    } .-;
}
```
> Assign the color names to @colors and you are good to go.

**Usage** (html)
```html
<div class="ui toggle pink checkbox">
    <input type="checkbox" tabindex="0" class="hidden">
    <label>Is this a rainbow?</label>
</div>
```
> [This overflow](http://stackoverflow.com/questions/21440789/#21441220) came in handy!
