### ISSUE TITLE
Colored text

### ISSUE THREAD

**Issue by piernik** [Semantic-Org/Semantic-UI#1885]
How to get colored text ex `class="ui blue text"`

**Comment by faller** [comment]
+1

**Comment by jlukic** [comment]
I understand the desire but I dont plan on adding colored text. I recommend just using css.

**Comment by JasonRodman** [comment]
I think this is one place semantic is lacking behind other frameworks. There needs to be some utility classes that we can use to apply common styles to any element without having to write custom css. Styles that have the same meaning no matter what component you apply time to. Some examples are common text color classes, text alignment, font weight classes, etc. I am sure we could think of a few more if need be. I find myself having to extend semantic to support these since I find them extremely useful since I write less css on a daily basis with them. I would urge you to reconsider your position on this. How do you plan to complete with bootstrap and foundation without at least having feature parity with them? These seem like no brainer bare minimum necessities to me.

**Comment by ivansglazunov** [comment]
+1
http://materializecss.com/color.html
Nice way to work with color
However, there may be too many CSS.
Why do I need it?
Standard CSS colors are very primitive and are not variable.
In design there is always at least 6, and sometimes 10-15 color states that you need to be able to apply to the background and font. The approach did not materialize so flexible.
I think it would be optimal to make a hybrid of:
Bootstrap
(text|bg)-danger (text-red) (text|bg)-warning (text-yellow) ...
Materialize
(text|bg)-(darken|lighten)-1 (12%) 2 (24%) 3 (36%)

**Comment by destan** [comment]
:+1:  colored text is surely a need. Why wouldn't you consider adding it @jlukic ?

Would you merge if somebody make a pr?

**Comment by hardy2defy** [comment]
please add some color

**Comment by yaboi** [comment]
+1

**Comment by kevspadilla** [comment]
+1

**Comment by chen-ye** [comment]
+1

**Comment by levithomason** [comment]
+1

**Comment by ilikebits** [comment]
:+1:

**Comment by m0nzderr** [comment]
+1

**Comment by Panman8201** [comment]
@jlukic I think it's useful so that colors match the theme's / Less colors. Sure, someone could make their own classes, but not having to worry about future color changes is +:100: Please re-consider.

**Comment by athyuttamre** [comment]
+1

**Comment by stej4n** [comment]
+1. It's very annoying. Why is it possible to create a blue button and not a blue text ??

**Comment by eeng** [comment]
+1

**Comment by Konard** [comment]
+1

**Comment by rpsirois** [comment]
+1

**Comment by serus22** [comment]
+1

**Comment by FSerg** [comment]
+1

**Comment by getnas** [comment]
+1

**Comment by joshbodine21** [comment]
+ 1...I find the need for this all the time and it is annoying to have to manage my own custom CSS just to match colors available in other Semantic-UI components.

**Comment by Atokulus** [comment]
+1

**Comment by rolandkofler** [comment]
+1

**Comment by brendon** [comment]
+1

**Comment by groeneveld91** [comment]
+1 :)

**Comment by krtschmr** [comment]
poor. just ridiculous!

**Comment by JasonRodman** [comment]
So how many +1's do we need before this gets reconsidered?

**Comment by krtschmr** [comment]
of course, just because every other css frameworks is having those classes.

**Comment by ivantcholakov** [comment]
+1

**Comment by rodoneill** [comment]
-1

**Comment by destan** [comment]
@rodoneill it's kind of obvious and already mentioned why would anyone wants to have this feature. However it's not obvious why would anyone doesn't want it. Would you be kind enough to elaborate on your `-1`?

**Comment by dgbrunoh** [comment]
+1

**Comment by JohnnyDevNull** [comment]
+1

I switched from bootstrap an also there are some small colored text classe. Its now over a year and so many people want this feature. Why this will not be added?

**Comment by Ryadnov** [comment]
+1

**Comment by CodeAnimal** [comment]
+1

**Comment by paper777** [comment]
+1

**Comment by tarundhillon** [comment]
+1 please reconsider

**Comment by seibelj** [comment]
+1

**Comment by frangeris** [comment]
+1

**Comment by IonutBajescu** [comment]
Hey chaps, the best method to support a feature request is to use the reactions (there's a thumbs up in the first post - click on it and show your affection).

Posting *+1* only lowers the chances of it being implemented as it annoys everyone that's watching the project. (~1k guys so far receive an email everytime someone posts a +1)

Thanks a lot.

**Comment by blesh** [comment]
Does anyone know if there's already a fork with this feature?

**Comment by kamalkhan** [comment]
One could add the following in `site/globals/site.overrides`

```less
@text-colors: blue, green, orange, pink, purple, red, teal, yellow, black, grey, white;
.text {
    .-(@i: length(@text-colors)) when (@i > 0) {
    	@c: extract(@text-colors, @i);
        &.@{c} { color: @@c }
        .-((@i - 1));
    }.-;
}
```

Which would generate:

```css
.text.white {
  color: #FFFFFF;
}
.text.grey {
  color: #CCCCCC;
}
.text.black {
  color: #1B1C1D;
}
.text.yellow {
  color: #F2C61F;
}
.text.teal {
  color: #00B5AD;
}
.text.red {
  color: #D95C5C;
}
.text.purple {
  color: #564F8A;
}
.text.pink {
  color: #D9499A;
}
.text.orange {
  color: #E07B53;
}
.text.green {
  color: #5BBD72;
}
.text.blue {
  color: #3B83C0;
}
```

And could be used as:
```html
<span class="red text">I am red!</span>
```
