### ISSUE TITLE
Columns Example from Documentation renders differently.

### ISSUE THREAD

**Issue by hickscorp** [Semantic-Org/Semantic-UI#1893]
From the Divider Documentation, i've assembled a snippet looking like so:
```haml
%body
  .ui.page.grid
    .ui.two.column.middle.aligned.relaxed.fitted.stackable.grid
      .column
        .ui.form.segment
          %h4.ui.dividing.header Column 1
      .ui.vertical.divider
        Or
      .center.aligned.column
        .ui.form.segment
          %h4.ui.dividing.header Column 2
```

Here is the CSS for this test:
```scss
//= require 'semantic-ui/dist/semantic'
//= require_self

html, body {
  margin:       0;
  padding:      0;
}
```

Most importantly, it doesn't place the columns horizontally: 
![larger screen](https://cloud.githubusercontent.com/assets/822933/6432330/01528130-c045-11e4-82b2-149d38d26ba6.jpg)

And on small screens, it renders with a larger gutter on the right than on the left: ![small screen](https://cloud.githubusercontent.com/assets/822933/6432327/e86f4b94-c044-11e4-9f32-39cbf171d1e5.jpg)

Is that a known bug, or is there something i'm doing incorrectly here?
