### ISSUE TITLE
Feature request: Opacity setting for Dimmer.

### ISSUE THREAD

**Issue by tmikaeld** [Semantic-Org/Semantic-UI#1897]
No more no less.

**Comment by jlukic** [comment]
You can do this by specifying the background color on a dimmer

```css
.my.dimmer {
  background-color: rgba(0, 0, 0, 0.5);
}
```

However this isn't probably obvious or convenient
