### ISSUE TITLE
Cards in android native browser 4

### ISSUE THREAD

**Issue by zh1lu0** [Semantic-Org/Semantic-UI#1939]
Seems native browser in  android below 4.4 does not support flexbox-wrap: wrap , it will broke layout.
![qq20150312-2 2x](https://cloud.githubusercontent.com/assets/9718362/6620214/802727e0-c90a-11e4-99b9-57d287202c5d.jpg)

**Comment by jlukic** [comment]
Hmm using chrome emulation of "Samsung Galaxy Note 3" i'm not seeing the wrap issues.

However I know 2009 flexbox syntax does not support `flex-wrap: wrap` . 

Since I cant emulate the behavior, can you try adding this rule to see if it fixes? This is the 2009 syntax

```css
.ui.cards {
  -moz-box-lines: multiple;
  -webkit-box-lines: multiple;
  box-lines: multiple;
}
```
