### ISSUE TITLE
iOS overflow fix makes it impossible to interact with scroll

### ISSUE THREAD

**Issue by apendua** [Semantic-Org/Semantic-UI#1979]
There's is an iOS fix, which looks like this:
```css
/*
  iOS incorrectly sizes document when content
  is presented outside of view with 2Dtranslate
*/

html.ios {
  overflow-x: hidden;
  -webkit-overflow-scrolling: touch;
}
```
It looks like it's really important. Unfortunately, it looks like when the fix is applied, it's no longer possible to get the current scroll position (not even vertical) and `window.pageYOffset` always return 0.

Is there a way to have cake and eat cake?
