### ISSUE TITLE
UI cards flex not wrapping on iOS and desktop Safari and a way to fix it

### ISSUE THREAD

**Issue by DHNCarlos** [Semantic-Org/Semantic-UI#1982]
Today I stumbled onto an issue where flex wrapping for `.ui.<x>.doubling.cards`. The issue is that, e.g. Safari on iOS 8 and Safari 8.0.2 on Yosemite, the current flex wrap does not wrap.

The way to fix it is to explicitly define the card width in flex.

Example:

```css
.ui.four.cards > .card {
    -webkit-flex: 0 0 -webkit-calc(25% - 1.5em); /* This needs to be added for wrapping to work properly */
    width: -webkit-calc( 25%  -  1.5em );
    width: calc( 25%  -  1.5em );
    margin-left: 0.75em;
    margin-right: 0.75em;
}
```
