### ISSUE TITLE
Invalid CSS in 1.11.5

### ISSUE THREAD

**Issue by smangelsdorf** [Semantic-Org/Semantic-UI#2024]
I'm using Semantic UI 1.11.5 via http://rails-assets.org and hitting a CSS syntax error which didn't exist in 1.11.4

The erroneous CSS is:

```css
/* Menu Item */

.ui.selection.dropdown .menu > .item {
  border-top: 1px solid rgba(0, 0, 0, 0.05);
  padding-left: 1.1em !important;
  /* Add in spacing for scroll bar */
  padding-right: -webkit-calc( 1.1em  + 1em) !important~;     // <--- here
  padding-right: calc( 1.1em  + 1em) !important~;             // <--- here
  white-space: normal;
  word-wrap: normal;
}
```

Problem code seems to be introduced in 776b6542, and to my eye looks to have imbalanced `~` characters. I'm not familiar enough with LESS to say what this *should* be, otherwise this would be a pull request.
