### ISSUE TITLE
Request for responsive views with compact information

### ISSUE THREAD

**Issue by peterfyj** [Semantic-Org/Semantic-UI#2064]
Existing responsive views (such as `Item`, `Card`, `List`) present stackable images on mobile devices, which take most of the screen space. I've always been expecting some responsive view that 1) on mobile devices has a small and fixed image on the left while the compact details are presented on the right. 2) present normal information on pc as existing views do such as `Card`.

For mobile websites such as amazon or ebay, I believe it is expected that we could see several items within the screen, while stackable and large images may be helpless.

**Comment by isaacqc** [comment]
I face the same situation. And I find that the Comment view has the mobile layout presentation that satisfies peterfyj 's first point as well as my need.
> 1) on mobile devices has a small and fixed image on the left while the compact details are presented on the right. 

but I'm afraid using it would hurt my websites SEO because the class names of Comment view does not reflect the content at all.

**Comment by isaacqc** [comment]
A temporary workaround is to comment out the following in item.less when building semantic-ui...

```less
/* Tablet Only */
@media only screen and (min-width: @tabletBreakpoint) and (max-width: @largestTabletScreen) {
  .ui.items > .item {
    margin: @tabletItemSpacing 0em;
  }
  .ui.items > .item > .image:not(.ui) {
    width: @tabletImageWidth;
  }
  .ui.items > .item > .image + .content {
    display: block;
    padding: 0em 0em 0em @tabletContentImageDistance;
  }

}

/* Mobily Only */
@media only screen and (max-width: @largestMobileScreen) {
  .ui.items > .item {
    margin: @mobileItemSpacing 0em;
  }
  .ui.items > .item > .image {
    display: block;
    margin-left: auto;
    margin-right: auto;
  }
  .ui.items > .item > .image,
  .ui.items > .item > .image > img {
    max-width: 100% !important;
    width: @mobileImageWidth !important;
    max-height: @mobileImageMaxHeight !important;
  }
  .ui.items > .item > .image + .content {
    display: block;
    padding: @mobileContentImageDistance 0em 0em;
  }

}
```
