### ISSUE TITLE
[Input] Fluid icon input bug

### ISSUE THREAD

**Issue by MrFusion42** [Semantic-Org/Semantic-UI#2117]
The `.ui.fluid.input` looks odd, the input field does not take the container's full width, but the icon is at the correct position.
![image](https://cloud.githubusercontent.com/assets/2915101/7153520/56e2e410-e312-11e4-812a-18ec7f6c441d.png)
(taken from http://semantic-ui.com/elements/input.html#fluid)

Changing the rule in [input.less:399](https://github.com/Semantic-Org/Semantic-UI/blob/master/src/definitions/elements/input.less#L399) from

```less
.ui.fluid.input {
  display: block;
}
```
to
```less
.ui.fluid.input {
  display: flex;
}
```
seems to solve the problem.
