### ISSUE TITLE
Dropdown inside input group should not have rounded corners

### ISSUE THREAD

**Issue by ahtinurme** [Semantic-Org/Semantic-UI#2202]
The issue can be seen here:
http://jsfiddle.net/5xj2zLaa/2/

Seems that you just need to add an exclusion, something like this:
```css
.ui.input .dropdown {
  border-radius: 0;
  -webkit-transition: none;
  transition: none;
}
```
