### ISSUE TITLE
Vertical Divider with icon it not middle anymore.

### ISSUE THREAD

**Issue by youyi1314** [Semantic-Org/Semantic-UI#2219]
I can't found any solution for Vertical Divider with icon and middle it?

My Code Below:
<div class="ui two column middle aligned relaxed fitted stackable grid">
<div class="column">
	Message
</div>
<div class="ui vertical divider">
	<i class="wait icon"></i>
</div>
<div class="column">
	New Update
</div>
</div>
With Icon:
![untitled](https://cloud.githubusercontent.com/assets/8391468/7490824/6a9b325e-f416-11e4-95e8-07d56fd49c53.png)

With Text:
![untitled](https://cloud.githubusercontent.com/assets/8391468/7490842/8f05c546-f416-11e4-9040-556f89857017.png)

Thanks

**Comment by ikourfaln** [comment]
Use this CSS to fix it:
```css
@media only screen and (min-width: 768px) {
  .ui.vertical.divider i.icon{
	line-height: 0;
  }
}
```
