### ISSUE TITLE
Add vertical align for table cells

### ISSUE THREAD

**Issue by ahtinurme** [Semantic-Org/Semantic-UI#2226]
Just a thought, but since I'm using those, I had to basically generate them myself:

```css
.ui.table[class*="top aligned"],
.ui.table [class*="top aligned"] {
  vertical-align: top;
}

.ui.table[class*="middle aligned"],
.ui.table [class*="middle aligned"] {
  vertical-align: middle;
}

.ui.table[class*="bottom aligned"],
.ui.table [class*="bottom aligned"] {
  vertical-align: bottom;
}
```
etc.
