### ISSUE TITLE
disabled field opacity

### ISSUE THREAD

**Issue by avalanche1** [Semantic-Org/Semantic-UI#2253]
Is it ok that in the first declaration opacity is set to 0.5 and in the 3rd to 1 once again?
```css
/*--------------------
       Disabled
---------------------*/

.ui.form .field :disabled,
.ui.form .field.disabled {
  opacity: 0.5;
}

.ui.form .field.disabled label {
  opacity: 0.5;
}

.ui.form .field.disabled :disabled {
  opacity: 1;
}
```

**Comment by jlukic** [comment]
These rules are incorrect, I'm also not sure why  they dont have variables or use global `@disabledOpacity`

**Comment by avalanche1** [comment]
You left
```css
.ui.form .field.disabled :disabled {
  opacity: 1;
}
```
unchanged. Is it by design?
