### ISSUE TITLE
Don't Use Important

### ISSUE THREAD

**Issue by wetux** [Semantic-Org/Semantic-UI#2257]
Please stop using !important in semantic stylesheet. I would like to be able to use custom stylesheet for overrides without having to resort to using !important on every element.

Example use;

```HTML
<link rel="stylesheet" href="styles/semantic.min.css">
<link rel="stylesheet" href="styles/custom.min.css">
```

```CSS
/* overrides padding in list item */
.ui.item {
  padding: 0;
}
```

Right now "!important" must be used everywhere.
