### ISSUE TITLE
Multiple Select - problem with long texts

### ISSUE THREAD

**Issue by kvetoslavnovak** [Semantic-Org/Semantic-UI#2288]
Hello, 

if I use long texts for multiselect, they escape their container:
![2select](https://cloud.githubusercontent.com/assets/5719547/7753171/f22a2f4e-ffe3-11e4-9481-52a443b77dac.jpg)

**Comment by jlukic** [comment]
```css
.ui.multiple.dropdown>.label {
  white-space: normal
}
```
Adding tomorrow
