### ISSUE TITLE
Divider text margin when stacked

### ISSUE THREAD

**Issue by oytuntez** [Semantic-Org/Semantic-UI#2311]
First things first:

```html
<div class="ui two column row middle aligned very relaxed fitted stackable">
    <div class="column">
        <a class="ui green button">Upload a document</a>
        <input type="file" name="documents" multiple="multiple" class="ui input hidden"/>
    </div>
    <div class="ui vertical divider">
        Or
    </div>
    <div class="center aligned column">
        <a class="ui green button">Enter your text</a>
        <textarea class="ui input hidden"></textarea>
    </div>
</div>
```

This is how it looks:

![Screenshot]
(http://i58.tinypic.com/x60arr.png)

When I override the definition like this, it aligns better (from 50% to 52%):
```css
.ui.stackable.grid .ui.vertical.divider:before,
  .ui.grid .stackable.row .ui.vertical.divider:before {
    margin-left: -(52% + @horizontalDividerMargin);
  }
```

I'm not sure if this is the ideal way to go. If it is, I'll make a PR for divider definition.
