### ISSUE TITLE
Modal size

### ISSUE THREAD

**Issue by h2u** [Semantic-Org/Semantic-UI#240]
Is there a way to call "small" modal.
Current modal is too large for messages like... "Remove that post?" :)

**Comment by dkzeb** [comment]
I added support for tiny sizes too in the css - add this to your css file under modal / size - currently around line 30000:
``` css
/* Tiny Modal Width */

@media only screen and (max-width: 767px) {
  .ui.tiny.modal {
    width: 95%;
    margin: 0em 0em 0em -47.5%;
  }
}

@media only screen and (min-width: 768px) {
  .ui.tiny.modal {
    width: 50%;
    margin: 0em 0em 0em -25%;
  }
}

@media only screen and (min-width: 992px) {
  .ui.tiny.modal {
    width: 200px;
    margin: 0em 0em 0em -100px;
  }
}

@media only screen and (min-width: 1200px) {
  .ui.tiny.modal {
    width: 300px;
    margin: 0em 0em 0em -150px;
  }
}

@media only screen and (min-width: 1920px) {
  .ui.tiny.modal {
    width: 400px;
    margin: 0em 0em 0em -200px;
  }
}
```
And you can assign the tiny class to the modal - useful for prompts and stuff
