### ISSUE TITLE
Request success state on Form

### ISSUE THREAD

**Issue by gluons** [Semantic-Org/Semantic-UI#2406]
Success state (and other like warning, info) is important. Please let it be avaliable in [Form] (http://semantic-ui.com/collections/form.html).

```html
<div class="ui form">
    <div class="field success">
        <label>Username</label>
        <input placeholder="Username" type="text">
    </div>
</div>
```

**Comment by jlukic** [comment]
There's an undocumented `success` state on form. Which will show success message in form, but there is no input styles for success.

I've added this as an enhancement.

**Comment by gluons** [comment]
Now, I can't find this in Semantic-UI 2.
I've tried to create custom success state.

![Success State](http://i57.tinypic.com/1i0unr.jpg)

```css
.ui.form .field.success label {
	color: #308330;
}
.ui.form .field.success input {
	background: #f4faf4 none repeat scroll 0 0;
	border-color: #a3c293;
	border-radius: 0.285714rem;
	box-shadow: none;
	color: #308330;
}
/* Success Placeholder */
.ui.form .success ::-webkit-input-placeholder {
	color: #5e9e5e;
}
.ui.form .success ::-ms-input-placeholder {
	color: #5e9e5e;
}
.ui.form .success ::-moz-placeholder {
	color: #5e9e5e;
}
.ui.form .success :focus::-webkit-input-placeholder {
	color: #558e55;
}
.ui.form .success :focus::-ms-input-placeholder {
	color: #558e55;
}
.ui.form .success :focus::-moz-placeholder {
	color: #558e55;
}
```
