### ISSUE TITLE
Small CSS bug - menu.css - vertical label missing units

### ISSUE THREAD

**Issue by alexmargineanu** [Semantic-Org/Semantic-UI#260]
``` css
.ui.vertical.menu .item > .label {
  float: right;
  min-width: 2.5;
  text-align: center;
}
```

I guess it should be **min-width: 2.5em**;
