### ISSUE TITLE
[Form] Inline Fields > .ui.icon.input has wrong width

### ISSUE THREAD

**Issue by malacalypse** [Semantic-Org/Semantic-UI#2621]
http://jsfiddle.net/p3Ln4fhm/1/

Inputs such as .ui.icon.input within .inline.fields have the wrong width - looks like they are explicitly set to 0 instead of letting flex handle the width.

**Comment by jlukic** [comment]
Related https://github.com/Semantic-Org/Semantic-UI/issues/2057

**Comment by gsmith-daed** [comment]
It's coming from form.less:123

```css
.ui.form .ui.input > input {
  width: 0 !important
}
```

Adding this to input.overrides "fixes" it for icon inputs. Not sure what else is broken:

```css
.ui.form .inline .ui.icon.input > input {
  width: inherit !important;
}
```

Have to get very specific to override that !important property
