### ISSUE TITLE
Cursor on checkbox label set to auto?

### ISSUE THREAD

**Issue by dalgard** [Semantic-Org/Semantic-UI#2684]
Why is the cursor on checkbox labels now set like this?

```css
.ui.checkbox label {
  cursor: auto;
}
```

Shouldn't it be set to `pointer`?
