### ISSUE TITLE
Parameterize the semantic namespace

### ISSUE THREAD

**Issue by cloud-walker** [Semantic-Org/Semantic-UI#2753]
It would be nice to have the "ui" namespace configurable, and use it via interpolation, like this:

```less
@namespace: ui;

// Button example
.@{namespace}.button
  border: 1px solid
```

This way will become possible to have multiple semantic version on our codebase, or avoid namespace collisions with other libraries.

What do you think?
