### ISSUE TITLE
[Build Tools] Make Sure Optional Files Still Receive LESS Errors

### ISSUE THREAD

**Issue by 100ideas** [Semantic-Org/Semantic-UI#2904]
A user might make a typo in an optional less component file, for instance, they might forget to end a line with a semicolon in their `@{siteFolder}/globals/site.variables` file:

``` less
/*******************************
     User Global Variables
*******************************/
@fontName          : 'Open Sans'
```

The less parser will hit the typo, error out, and skip parsing the rest of the file, but because the file is included `optional`ly by default by `src/theme.less`,

``` less
/*******************************
        Import Directives
*******************************/
@theme : @@element;

/*--------------------
   Site Variables
---------------------*/

/* Default */
@import "@{themesFolder}/default/globals/site.variables";

/* Packaged Theme */
@import (optional) "@{themesFolder}/@{site}/globals/site.variables";

/* Site Theme */
@import (optional) "@{siteFolder}/globals/site.variables";
```

apparently no error is logged to the user's console. This is confusing to new Semantic-UI theme developers, whose first steps may involve editing / overriding definitions with their `site/globals/site.variables` file. If they make a typo in that file, the entire file will be **silently** ignored by less / gulp, and the new developer will not understand why their modifications are not being included by the build system.

Is it possible to throw errors on `optional`ly included less files?

---

**To reproduce this issue, follow these steps**

``` bash
npm install semantic-ui --save
cd semantic/
gulp build
(select automatic gulp config options)
```

The top of `src/theme.less` should resemble

``` less
/*******************************
        Import Directives
*******************************/

@theme : @@element;

/*--------------------
   Site Variables
---------------------*/

/* Default */
@import "@{themesFolder}/default/globals/site.variables";

/* Packaged Theme */
@import (optional) "@{themesFolder}/@{site}/globals/site.variables";

/* Site Theme */
@import (optional) "@{siteFolder}/globals/site.variables";
```

and the top of the compiled `dist/semantic.css` should resemble:

``` css
 /*
 * # Semantic UI - x.x
 * https://github.com/Semantic-Org/Semantic-UI
 * http://www.semantic-ui.com/
 *
 * Copyright 2014 Contributors
 * Released under the MIT license
 * http://opensource.org/licenses/MIT
 *
 */
@import url('https://fonts.googleapis.com/css?family=Lato:400,700,400italic,700italic&subset=latin');
```

The hypothetical developer wants to use default fonts instead of google fonts, so they add the following line to their `src/site/globals/site.variables`:

``` less
/*******************************
     User Global Variables
*******************************/
@importGoogleFonts : false
```

**Oops, they forgot to terminate the line with a semicolon.** Now they run gulp build again and look for the changes to`dist/semantic.css` - the `@import url(`'https://fonts.googleapis.com...` line should be absent. But it is still there. Hmmm... mystery.

If the `(optional)` modifier is removed from the `@{siteFolder}/globals/site.variables` `import` directive in `src\theme.less`, the problem is more obvious when `gulp build` runs.

``` less
/* Packaged Theme */
@import (optional) "@{themesFolder}/@{site}/globals/site.variables";

/* Site Theme */
@import "@{siteFolder}/globals/site.variables";
```

``` bash
↪ gulp build
[00:38:36] Using gulpfile ~/dev/Semantic-UI-bug/semantic/gulpfile.js
[00:38:36] Starting 'build'...
Building Semantic
[00:38:36] Starting 'build-javascript'...
Building Javascript
[00:38:36] Starting 'build-css'...
Building CSS
[00:38:36] Starting 'build-assets'...
Building assets
[gulp] Created: dist/components/site.js
[gulp] Created: dist/components/site.min.js
[gulp] Created: dist/components/form.js
[gulp] Created: dist/components/accordion.js
[gulp] Created: dist/components/form.min.js
[gulp] Created: dist/components/checkbox.js
[gulp] Created: dist/components/accordion.min.js
[gulp] Created: dist/components/dimmer.js
[gulp] Created: dist/components/checkbox.min.js
[gulp] Created: dist/components/dimmer.min.js
[gulp] Created: dist/components/dropdown.js
[gulp] Created: dist/components/embed.js
[gulp] Created: dist/components/dropdown.min.js
[gulp] Created: dist/components/modal.js
[gulp] Created: dist/components/embed.min.js
{ [Error: Unrecognised input. Possibly missing something in file /Users/100ideas/dev/Semantic-UI-bug/semantic/src/site/globals/site.variables line no. 4]
  type: 'Parse',
  filename: '/Users/100ideas/dev/Semantic-UI-bug/semantic/src/site/globals/site.variables',
  index: 119,
  line: 4,
  callLine: NaN,
  callExtract: undefined,
  column: 26,
  extract: 
   [ '*******************************/',
     '@importGoogleFonts : false',
     undefined ],
  message: 'Unrecognised input. Possibly missing something in file /Users/100ideas/dev/Semantic-UI-bug/semantic/src/site/globals/site.variables line no. 4',
  stack: undefined,
  lineNumber: 4,
  fileName: '/Users/100ideas/dev/Semantic-UI-bug/semantic/src/site/globals/site.variables',
  name: 'Error',
  showStack: false,
  showProperties: true,
  plugin: 'gulp-less',
  __safety: { toString: [Function] } }
```

As a positive control, note that if the typo is fixed in `@{siteFolder}/globals/site.variables`

``` less
@fontName          : 'Open Sans';
```

and the global site.variables are left as optional in `theme.less` 

``` less
@import (optional) "@{siteFolder}/globals/site.variables";
```

then `grunt build` succeeds without errors and the google font directives are missing from the top of  `semantic.css` as expected

``` less
 /*
 * # Semantic UI - x.x
 * https://github.com/Semantic-Org/Semantic-UI
 * http://www.semantic-ui.com/
 *
 * Copyright 2014 Contributors
 * Released under the MIT license
 * http://opensource.org/licenses/MIT
 *
 */
/*!
 * # Semantic UI x.x - Reset
 * http://github.com/semantic-org/semantic-ui/
```

I don't know anything about gulp or the less parser / compiler. Is it possible to detect and pass on errors in optionally-included less files?
