### ISSUE TITLE
List inside message is a bit messed up

### ISSUE THREAD

**Issue by ahtinurme** [Semantic-Org/Semantic-UI#2958]
http://jsfiddle.net/gb0mbwjf/3/

Upper one is the current situation, below is the way it should be.

Problem seems to be:

```css
.ui.message ul.list {
    ...
    margin: .5em 0 0;
}
```
