### ISSUE TITLE
Marking dropdown menu item as active prevents it from being expanded

### ISSUE THREAD

**Issue by Neaox** [Semantic-Org/Semantic-UI#2978]
If you have a menu that contains a dropdown menu item and you mark that item as active (to indicate that it is the current area/page) then you are unable to expand/click on that item.

See this fiddle for an example: https://jsfiddle.net/52m76fzc/1/

Clicking on the active item does nothing clicking on the item next to it expands the dropdown item.

You should be able to mark an item as the active/current item while still being able to expand it.

**Comment by v3rron** [comment]
same problem here... when it's selected as active, the menu just opens and closes instantly in a moment

**Comment by paglias** [comment]
Any alternative until this gets fixed?

**Comment by komirad** [comment]
It's a conflict between menu item's `active` and dropdown's `active`. Perhaps dropdown's `active` should be renamed `open`.

**Comment by Zooll8** [comment]
@komirad I agree with you. `active` should be renamed to `open`

**Comment by Billybobbonnet** [comment]
Is there an existing class name to mark a menu dropdown item as `active` (as opposed to `open`), or should I write my own to achieve that?

**Comment by Billybobbonnet** [comment]
Actually, I just made a quick and dirty set of rules for the `current` class keyword in order to highlight active menu dropdowns. Tested for `inverted` with both `secondary` variation and none.

```CSS
.menu:not(.secondary) .dropdown.item.current{
  background: rgba(255,255,255,.15);
  color: #fff !important;
}
.menu:not(.secondary) .dropdown.item.current:after{
visibility: visible!important;
z-index: 100!important;
background: #3d3e3f !important;
margin: 0 !important;
box-shadow: none !important;
border: none !important;
}
.menu.inverted .dropdown.item.current{
border-color: #fff;
}
```
