### ISSUE TITLE
Dark Close Icon On Inverted Modal

### ISSUE THREAD

**Issue by caiotarifa** [Semantic-Org/Semantic-UI#3070]
Would `inverted modals` darken the close icon by default?

**JSFIDDLE**
http://jsfiddle.net/Lwgr9a6r/embedded/result/
See on `> 992px`.

**Comment by vinayakkulkarni** [comment]
Yep, this still happens 😞

**Comment by radix** [comment]
I worked around this by adding the following rule:

```css
.ui.inverted > .ui.modal > .close {
  color: #000;
}
```

I haven't tested thoroughly yet but it seems to work.
