### ISSUE TITLE
Semantic UI Flash feature.

### ISSUE THREAD

**Issue by silvercrow27** [Semantic-Org/Semantic-UI#3153]
Do you guys have a plan on adding a notification like notify.js in Semantic UI? I have tried to make one like notifyjs. The code for it is this.

```css
.ui.flash
  {
    background-color: rgba(0, 137, 71, 0.8);
    color:white;
    top:55px;
    right: 35px;
    font-size:13px;
    padding:20px 10px 20px 10px;
    position:absolute;
    height: auto;
    width: 20%;
    text-align: justify;
    z-index: 999;
  }
```
```javascript
$('.ui.button').on('click', function(){
  $('.ui.flash').hide().delay(800).fadeIn(800).delay(5000).fadeOut(300);
});
```
