### ISSUE TITLE
[REQUEST] Add disabled state to Tab Module (to the tab menu item)

### ISSUE THREAD

**Issue by shadoWalker89** [Semantic-Org/Semantic-UI#3178]
Is it possible to add disabled state to the Tab menu.
Disabled state will have to effects.
The tab menu item will be grayed out and it will not be clickable.

In some cases like in mine, it is useful to show that the tab exists but it is not available because of some condition.

**Comment by kmd1970** [comment]
Yes, please. class="disabled item"?

**Comment by kmd1970** [comment]
Workaround.

```css
.ui.tabular.menu > .disabled.item {
 opacity: 0.45 !important;	
}

\* bonus, nicer cursor *\
.disabled {
   cursor: not-allowed !important;
} 
```
