### ISSUE TITLE
[Modal] Add tiny and mini modal variations.

### ISSUE THREAD

**Issue by ismail-codar** [Semantic-Org/Semantic-UI#3214]
Large and small modal sizes can be applied #240 but noting for mini, tinny and other sizes.
Small modal  size is 720px on big screens. It is big for name, surname like inputs in the modal.

**Comment by Banandrew** [comment]
In the meantime, it doesn't take too much time to create your own; this example should look nicer with forms in general.

*src/site/modules/modal.ovverides:*

```css
/* Extra Small */
.ui.xsmall.modal > .header:not(.ui) {
  font-size: @xsmallHeaderSize;
}

/* Extra Small Modal Width */
@media only screen and (max-width : @largestMobileScreen) {
  .ui.xsmall.modal {
    width: @xsmallMobileWidth;
    margin: @xsmallMobileMargin;
  }
}
@media only screen and (min-width : @tabletBreakpoint) {
  .ui.xsmall.modal {
    width: @xsmallTabletWidth;
    margin: @xsmallTabletMargin;
  }
}
@media only screen and (min-width : @computerBreakpoint) {
  .ui.xsmall.modal {
    width: @xsmallComputerWidth;
    margin: @xsmallComputerMargin;
  }
}
@media only screen and (min-width : @largeMonitorBreakpoint) {
  .ui.xsmall.modal {
    width: @xsmallLargeMonitorWidth;
    margin: @xsmallLargeMonitorMargin;
  }
}
@media only screen and (min-width : @widescreenMonitorBreakpoint) {
  .ui.xsmall.modal {
    width: @xsmallWidescreenMonitorWidth;
    margin: @xsmallWidescreenMonitorMargin;
  }
}
```

*src/site/modules/modal.variables:*

```LESS
/*******************************
         Site Overrides
*******************************/

/*-----------------------------
      Modal Variations
-----------------------------*/

/* Size Widths */
@xsmallRatio: 0.4;

/* Derived Responsive Sizes */
@xsmallHeaderSize: 1.3em;
@xsmallMobileWidth: @mobileWidth;
@xsmallTabletWidth: (@tabletWidth * @xsmallRatio);
@xsmallComputerWidth: (@computerWidth * @xsmallRatio);
@xsmallLargeMonitorWidth: (@largeMonitorWidth * @xsmallRatio);
@xsmallWidescreenMonitorWidth: (@widescreenMonitorWidth * @xsmallRatio);

@xsmallMobileMargin: 0em 0em 0em -(@xsmallMobileWidth / 2);
@xsmallTabletMargin: 0em 0em 0em -(@xsmallTabletWidth / 2);
@xsmallComputerMargin: 0em 0em 0em -(@xsmallComputerWidth / 2);
@xsmallLargeMonitorMargin: 0em 0em 0em -(@xsmallLargeMonitorWidth / 2);
@xsmallWidescreenMonitorMargin: 0em 0em 0em -(@xsmallWidescreenMonitorWidth / 2);
```
