### ISSUE TITLE
Divider missing on a stacked menu item

### ISSUE THREAD

**Issue by palepal** [Semantic-Org/Semantic-UI#3269]
right item + item does not have a divider between them

``` html
<a href="#" class="ui right simple dropdown item">
    smth <i class="dropdown icon"></i>
    <div class="menu">
        <div class="item">Link Item</div>
        <div class="item">Link Item</div>
        <div class="divider"></div>
        <div class="header">Header Item</div>
        <div class="item">
            <i class="dropdown icon"></i>
            Sub Menu
            <div class="menu">
                <div class="item">Link Item</div>
                <div class="item">Link Item</div>
            </div>
        </div>
        <div class="item">smth</div>
    </div>
</a>
<a href="#" class="item">
    <i class="lock icon"></i>
</a>
```

![mia](https://cloud.githubusercontent.com/assets/8116046/10863706/96b891be-7fe0-11e5-9c7d-dac0c977ca0b.png)

so maybe

``` css
.ui.menu:not(.vertical) .right.item + .item:after
{
    position: absolute;
    content: '';
    top: 0;
    left: 0;
    height: 100%;
    width: 1px;
    background: rgba(34,36,38,.1);
}
```
