### ISSUE TITLE
Modal window with bug

### ISSUE THREAD

**Issue by batata004** [Semantic-Org/Semantic-UI#3307]
Hi,

I created a modal window and it works fine, I mean, I use class "modal small" and the modal is beautifull and responsive. However I want the window to be a little smaller, with 300px of width. So I followed some good advices online and made 

width:300px; margin-left:-150px;

Some people told me to make the margin-left half of the width and negative. It works perfectly! :) But when I reduce the browser window size to less than 300px the modal window does NOT go below 300px. Of course, I set width to 300px! So I changed it to:

max-width:300px; margin-left:-150px;

This works fine too but there are a few serious bugs. When I call ".modal('show');" the modal window does not show centralized, it is slithely to the left (about 80px). Ok, not a big problem. But when I reduce the browser window size to 250px (for example) the modal window reduces it's size automatically (great!) but it moves itself outside of the browser window for about 100px and I only see a small part of the modal window.

This is a bug easy to reproduce and other people also noted this on the internet but for some reason nobody cared to report. I hope you can fix this or tell me the right way to reduce the size of the modal window to a custom width without using "hacks" like setting "margin-left".

**Comment by Banandrew** [comment]
Hey,

It's very easy to do, you need to add a custom smaller variation of a modal. Add this to `semantic/src/site/modules/modal.variables`:

``` LESS
/* Size Widths */
@xsmallRatio: 0.4;

/* Derived Responsive Sizes */
@xsmallHeaderSize: 1.3em;
@xsmallMobileWidth: @mobileWidth;
@xsmallTabletWidth: (@tabletWidth * @xsmallRatio);
@xsmallComputerWidth: (@computerWidth * @xsmallRatio);
@xsmallLargeMonitorWidth: (@largeMonitorWidth * @xsmallRatio);
@xsmallWidescreenMonitorWidth: (@widescreenMonitorWidth * @xsmallRatio);

@xsmallMobileMargin: 0em 0em 0em -(@xsmallMobileWidth / 2);
@xsmallTabletMargin: 0em 0em 0em -(@xsmallTabletWidth / 2);
@xsmallComputerMargin: 0em 0em 0em -(@xsmallComputerWidth / 2);
@xsmallLargeMonitorMargin: 0em 0em 0em -(@xsmallLargeMonitorWidth / 2);
@xsmallWidescreenMonitorMargin: 0em 0em 0em -(@xsmallWidescreenMonitorWidth / 2);
```

And this to `semantic/src/site/modules/modal.overrides`:

``` LESS
/* Extra Small */
.ui.xsmall.modal > .header:not(.ui) {
  font-size: @xsmallHeaderSize;
}

/* Extra Small Modal Width */
@media only screen and (max-width : @largestMobileScreen) {
  .ui.xsmall.modal {
    width: @xsmallMobileWidth;
    margin: @xsmallMobileMargin;
  }
}
@media only screen and (min-width : @tabletBreakpoint) {
  .ui.xsmall.modal {
    width: @xsmallTabletWidth;
    margin: @xsmallTabletMargin;
  }
}
@media only screen and (min-width : @computerBreakpoint) {
  .ui.xsmall.modal {
    width: @xsmallComputerWidth;
    margin: @xsmallComputerMargin;
  }
}
@media only screen and (min-width : @largeMonitorBreakpoint) {
  .ui.xsmall.modal {
    width: @xsmallLargeMonitorWidth;
    margin: @xsmallLargeMonitorMargin;
  }
}
@media only screen and (min-width : @widescreenMonitorBreakpoint) {
  .ui.xsmall.modal {
    width: @xsmallWidescreenMonitorWidth;
    margin: @xsmallWidescreenMonitorMargin;
  }
}
```

Then rebuild semantic. Don't think about it too much, if you need to create another bigger or even smaller version, just add another variable like an `@xsmallRatio`, set it to whatever you need and copy-paste it to your custom `/* Derived Responsive Sizes */` while creating those variables as well. Then copy-paste those to `@media` in `modal.overrides`.

An `@xsmallRatio` of 0.4 should give you a modal with a width of 320px—or something like that, I don't remember exactly, honestly, but anyway, just for an example for you to better understand ratios, here're modal ratios for a default theme that you probably saw in documentation:

``` LESS
/* Size Widths */
@smallRatio: 0.8;
@largeRatio: 1.2;
```

**Comment by gilperon** [comment]
@Banandrew thanks a LOT! You provided a great way to fix this but I am building an app that has a certification and I need to use CDN to things like jquery, semantic-ui... I cant change "custom" files cause I use this:

<link rel="stylesheet" type="text/css" href="//oss.maxcdn.com/semantic-ui/2.1.6/semantic.min.css" />
<script src="//oss.maxcdn.com/semantic-ui/2.1.6/semantic.min.js"></script>

Any idea how I can solve this problem keeping my app certification?

**Comment by Banandrew** [comment]
That's a bummer. I'm not sure if it will work, but try to add this to your custom CSS that gets loaded after Semantic UI's:

``` CSS
/*******************************
         Site Overrides
*******************************/

/* Extra Small */
.ui.xsmall.modal > .header:not(.ui) {
  font-size: 1.3em;
}

/* Extra Small Modal Width */
@media only screen and (max-width: 767px) {
  .ui.xsmall.modal {
    width: 95%;
    margin: 0em 0em 0em -47.5%;
  }
}

@media only screen and (min-width: 768px) {
  .ui.xsmall.modal {
    width: 35.2%;
    margin: 0em 0em 0em -17.6%;
  }
}

@media only screen and (min-width: 992px) {
  .ui.xsmall.modal {
    width: 340px;
    margin: 0em 0em 0em -170px;
  }
}

@media only screen and (min-width: 1200px) {
  .ui.xsmall.modal {
    width: 360px;
    margin: 0em 0em 0em -180px;
  }
}

@media only screen and (min-width: 1920px) {
  .ui.xsmall.modal {
    width: 380px;
    margin: 0em 0em 0em -190px;
  }
}
```

Semantic UI calculates this stuff, so I just basically took the code from before, opened `semantic.css`, found everything related to `xsmall` and copy-pasted here. What I'm saying, is if you don't like this modal size, just install Semantic UI locally and do the same thing using the ratio you need.
