### ISSUE TITLE
[List] File image icon has more right padding than other icons

### ISSUE THREAD

**Issue by andreyvk** [Semantic-Org/Semantic-UI#3324]
Hi,

Seems that padding is overridden by list images. Firebug shows that this one is the culprit:

``` css
.ui.list .list > .item > .image:not(:only-child):not(img), 
.ui.list > .item > .image:not(:only-child):not(img) {
    padding-right: 0.5em;
}
```

Here's a [fiddle](http://jsfiddle.net/andreyvk/ehwxq393/)
