### ISSUE TITLE
.ui.container & .right.menu: no right border

### ISSUE THREAD

**Issue by louwers** [Semantic-Org/Semantic-UI#3332]
```html
  <div class="ui fixed icon menu">
    <div class="ui container">
      <a class="item"><i class="chevron left icon"></i></a>
      <a class="item"><i class="chevron right icon"></i></a>
      <div class="right menu">
        <a class="item"><i class="info icon"></i></a>
        <a class="item"><i class="archive icon"></i></a>
      </div>
    </div>
  </div>
```
As can be seen here: the last item of the right menu does not have a border on the right:
![screen shot 2015-11-14 at 15 22 14](https://cloud.githubusercontent.com/assets/649392/11163964/86aab4ce-8ae3-11e5-88fa-0d896facc09d.png)
http://jsfiddle.net/2nsp71f7/3/

**Comment by louwers** [comment]
Quick fix:
```css
.ui.menu .item:before,
.ui.menu .right.menu .item:last-of-type:after { /* this line is the quick fix */
  position: absolute;
  content: '';
  top: 0%;
  right: 0px;
  height: 100%;
  width: 1px;
  background: rgba(34, 36, 38, 0.1);
}
```
For a more permanent solution, I think [this](https://github.com/Semantic-Org/Semantic-UI/commit/2aa70665008395614bb3ac6d60d958572e1e5e55) needs to be taken a look at.
