### ISSUE TITLE
Changing the font for all project (site, components...)

### ISSUE THREAD

**Issue by maxcnunes** [Semantic-Org/Semantic-UI#3337]
I have installed semantic-ui version **2.1.6** in my project and the only thing I have changed in the `theme.config` is:
```less
// @site       : 'default';
@site       : 'material';
```

Although after running `gulp build` the `dist` files does not have the font applied for all project. The Roboto font is applied in some parts like:

```css
@import url('https://fonts.googleapis.com/css?family=Roboto:400,700,400italic,700italic&subset=latin');
```
and
```css
body {
  margin: 0px;
  padding: 0px;
  overflow-x: hidden;
  min-width: 320px;
  background: #F9F9F9;
  font-family: 'Roboto', 'Helvetica Neue', Arial, Helvetica, sans-serif;
  font-size: 13px;
  line-height: 1.33;
  color: #212121;
  font-smoothing: antialiased;
}
```

But in other parts like cards it still using the default font Lato.
```css
.ui.cards > .card > .content > .header,
.ui.card > .content > .header {
  display: block;
  margin: '';
  font-family: 'Lato', 'Helvetica Neue', Arial, Helvetica, sans-serif;
  color: rgba(0, 0, 0, 0.85);
}
```

Should I have changed another configuration file to have the Roboto font applied for all project?

Thanks,
