### ISSUE TITLE
Is it possible to use the CSS masonry layouts on Semantic UI cards?

### ISSUE THREAD

**Issue by dragonfire1119** [Semantic-Org/Semantic-UI#3353]
Are you going to support the column css properties for masonry css card layouts? Example would be http://v4-alpha.getbootstrap.com/components/card/#columns

**Comment by jlukic** [comment]
I don't understand the question

**Comment by dragonfire1119** [comment]
Are the "Semantic UI" cards going to be able to look like the bootstrap card columns?

**Comment by jlukic** [comment]
You can achieve a masonry look by using grid columns and stacking different sized cards.

Most of SUI currently uses flexbox  which doesnt support IE9. (This is with 2.0)

**Comment by dragonfire1119** [comment]
@jlukic I'm using ui cards but they still are using the equal height? Is there a different way with grids?

**Comment by t2** [comment]
Looking for an answer here too.

**Comment by antoineschaller** [comment]
Same here, it would be great to add a masonry-like class for cards or grid on semantic

**Comment by krishaamer** [comment]
I also need this.

**Comment by dragonfire1119** [comment]
This is my solution to css masonry layout with ui cards.

``` sass
$mobileBreakpoint            : 320px;
$tabletBreakpoint            : 768px;
$computerBreakpoint          : 992px;
$largeMonitorBreakpoint      : 1200px;
$widescreenMonitorBreakpoint : 1920px;

.card-columns-four {
    -webkit-column-count: 4;
    -moz-column-count: 4;
    column-count: 4;
    -webkit-column-gap: 1rem;
    -moz-column-gap: 1.25rem;
    column-gap: 1.25rem;
    @media only screen and (min-width: $mobileBreakpoint) and (max-width: $tabletBreakpoint) {
		-webkit-column-count: 2;
		-moz-column-count: 2;
		column-count: 2;
	}
    @media only screen and (min-width: $tabletBreakpoint) and (max-width: $computerBreakpoint) {
		-webkit-column-count: 3;
		-moz-column-count: 3;
		column-count: 3;
	}
    .ui.card:first-child {
	    margin-top: 1px;
	}
    .ui.card {
    	display: inline-block;
    	margin: 1.0em 0;
    	margin-top: 1px;
    }
}
```

The markup >
``` HTML
<div class="card-columns-four">
     <div class="ui card">
           ....
     </div>
</div>
```

Hope this helps. 
Remember multi columns don't work on every browser version http://caniuse.com/#feat=multicolumn

**Comment by cdog** [comment]
Here it is an example using responsive grids:
http://jsfiddle.net/cdog/oj4ew4Le/embedded/result/

It introduces the `.masonry` modifier which applies to `.grid` preserving columns spacing.

```css
.masonry.grid {
  display: block;
}

@media only screen and (min-width: 768px) {
  .masonry.grid {
    -webkit-column-count: 2;
       -moz-column-count: 2;
            column-count: 2;
    -webkit-column-gap: 0;
       -moz-column-gap: 0;
            column-gap: 0;
  }

  .ui.doubling.masonry.grid[class*="three column"] > .column {
    width: 100% !important;
  }
}

@media only screen and (min-width: 992px) {
  .masonry.grid {
    -webkit-column-count: 3;
       -moz-column-count: 3;
            column-count: 3;
  }
}
```

```html
<div class="ui container">
  <div class="ui three column doubling stackable masonry grid">
    <div class="column">…</div>
    <div class="column">…</div>
    …
  </div>
</div>
```

Columns can hold any content not just cards. Using `.grid` instead of `.cards` also works with the `.relaxed` modifier.

```html
<div class="ui three column doubling stackable relaxed masonry grid">
```

When using cards inside a masonry grid don't forget to add the `.fluid` class.

```html
<div class="ui fluid card">…</div>
```
