### ISSUE TITLE
[Checkbox] inconsistent cursor

### ISSUE THREAD

**Issue by larsbo** [Semantic-Org/Semantic-UI#3355]
Using a checkbox with JavaScript gives the label a pointing cursor based on the following class:
```css
/* Selectable Label */
.ui.checkbox input.hidden + label {
  cursor: pointer;
  user-select: none;
}
```

The javascript-free version doesn't have a pointer cursor which makes sense if there is no ```for``` attribute referencing the input element.
Nevertheless if there is a ```for```attribute the pointing cursor should be enabled like this:
```css
.ui.checkbox input + label[for] {
  cursor: pointer;
  user-select: none;
}
```

I think this a small but useful improvement.
