### ISSUE TITLE
.ui.form .field:last-child where a hidden field is the last child breaks intent

### ISSUE THREAD

**Issue by brendon** [Semantic-Org/Semantic-UI#3392]
In a form where there is a `.hidden.field` as the last child, the last visible child doesn't get a `margin-bottom: 0em` which means the bottom of the form is too far from last visible field.

I'd propose:

```css
.ui.form .field:not(.hidden):last-child,
.ui.form .fields:last-child .field:not(.hidden) {
  margin-bottom: 0em;
}
```

or something like that.

**Comment by jlukic** [comment]
Seems reasonable

**Comment by brendon** [comment]
Thanks for that. Would you like a pull request or is it easier just to patch it on your end? :)

**Comment by jlukic** [comment]
I can add from what you've provided.

**Comment by jlukic** [comment]
After actually checking in the code, `hidden fields` is not a concept in semantic ui. So that's why theres no rule.

**Comment by brendon** [comment]
Lol, I fooled myself! Yes that's a custom modification I made in the first place! Sorry for wasting your time.

I added it because I'm using `simple_form` to generate forms in Rails and it was easier to work with its default output in which it appends the class `.hidden` to the `<div>` wrapping a hidden field.

The code I used (in case you think it's worth while adding it) was:

```css
.ui.form, .ui.form .fields {
  .hidden.field {
    margin: 0;
  }
}
```
