### ISSUE TITLE
Black border on attached inverted coloured segments

### ISSUE THREAD

**Issue by brendon** [Semantic-Org/Semantic-UI#3397]
Coloured inverted attached segments currently have a pretty jarring `#555555` border that usually doesn't look good in combination with the bold background colour.

What do you think of giving these segments the same border colour as their background colour?

```less
.ui.inverted.attached.segment {
  &.green {
    border-color: @green;
  }
}
```

Looking through your source code I see that the current `border-color` is set to `@solidWhiteBorderColor`. Which by default is `#555555`. Is that an error?
