### ISSUE TITLE
[List] - Bullets within simple list 

### ISSUE THREAD

**Issue by simply-moritz** [Semantic-Org/Semantic-UI#3436]
**Steps to Reproduce**
1. create a simple html unordered list 

``` html
<ul class="ui list">
  <li class="item">text 1</li>
  <li class="item">text 2</li>
</ul>
```

**Expected**
The List should show text without any list-style-types

**Result**
The List does not do this. In my opinion the bug is in semantic.css in line 13179 where a normal list is styled like a bullet list with a content attribute.

``` css
ul.ui.list li:before,
.ui.bulleted.list .list > .item:before,
.ui.bulleted.list > .item:before {
  -webkit-user-select: none;
  -moz-user-select: none;
  -ms-user-select: none;
  user-select: none;
  pointer-events: none;
  position: absolute;
  top: auto;
  left: auto;
  margin-left: -1.25rem;
  content: '•';
  opacity: 1;
  color: inherit;
  vertical-align: top;
}
```

**Testcase**
https://jsfiddle.net/uo05cb29/
