### ISSUE TITLE
Labeled number input

### ISSUE THREAD

**Issue by sebilasse** [Semantic-Org/Semantic-UI#3457]
The label hides the spinners (e.g. webkit) :
[fiddle](http://jsfiddle.net/29boek8c/)

```
<div class="ui input corner labeled">
  <input placeholder="Age" type="number">
  <div class="ui corner label">
    <i class="asterisk icon"></i>
  </div>
</div>
```

[edit]
this affects ONLY webkit w. Safari 6.1+
possible fix: [fiddle](http://jsfiddle.net/d7u3wynb/)

Also note that lesscss seems to need a special fix especially to support Safari 9.2 :

``` css
@media screen and (min-color-index:0) and(-webkit-min-device-pixel-ratio:0) {
  .ui.corner.labeled input[type="number"]::-webkit-inner-spin-button {
    position: relative;
    right: @labeledMargin;
  }
}
@supports (overflow:-webkit-marquee) and (justify-content:inherit) {
  .ui.corner.labeled input[type="number"]::-webkit-inner-spin-button {
    position: relative;
    right: @labeledMargin;
  }
}
```

[/edit]
