### ISSUE TITLE
Button inside input

### ISSUE THREAD

**Issue by elfassy** [Semantic-Org/Semantic-UI#3458]
I'd like to see something like this:

![screen shot 2015-12-11 at 8 58 34 am](https://cloud.githubusercontent.com/assets/311279/11745322/6660f662-9fe5-11e5-98b7-4b3d8992498a.png)

This image was generated with the following code:

``` html
<div class="ui action input">
      <input type="text" placeholder="Search...">
      <div class="ui  wrapper_name">
          <button class="ui blue button">Search</button>
     </div>
</div>
```

``` css
.ui.wrapper_name{
    border: 1px solid rgba(34, 36, 38, 0.14902);
    border-left: none;
    padding: 8px;
    border-radius: 0px 4px 4px 0px;
}
```

Ideas on what to name this `wrapper_name` class? See a better way to structure the code?
Thanks
