### ISSUE TITLE
[Dropdown] - Dropdown in a right vertical menu

### ISSUE THREAD

**Issue by Yopadd** [Semantic-Org/Semantic-UI#3661]
I would like a right menu icons with dropdown like this

```html
<div class="ui right fixed vertical menu icon">
  <div class ="ui dropdown item icon">
    <i class="setting icon"></i>
    <div class="menu">
      <div class="item">Options 1</div>
      <div class="item">Options 2</div>
      <div class="item">Options 3</div>
      <div class="item">Options 4</div>
    </div>
  </div>
</div>
``` 

But the dropdown appears on the right side. As a result it's outside screen.

I tried with `left` class

```html
<div class ="ui left dropdown item icon">
```
or
```html
 <div class="left menu">
```

But nothing's changed.

http://jsfiddle.net/Yopadd/od30vfpc/1/

**Comment by xDaizu** [comment]
Apparently the error is in the CSS line:
```css
.ui.dropdown .menu .left.menu, .ui.dropdown > .left.menu .menu {
    border-radius: 0.285714rem !important;
    left: auto !important;
    right: 100% !important;
}
```
I changed it to :

```css
.ui.dropdown .menu .left.menu, .ui.dropdown > .left.menu {
    border-radius: 0.285714rem !important;
    left: auto !important;
    right: 100% !important;
}
```
and now seems to work alright. Con you check it out here in this [jsFiddle](http://jsfiddle.net/73z5thtc/1/)
