### ISSUE TITLE
Popup weird behavior after modal close

### ISSUE THREAD

**Issue by MeKarina** [Semantic-Org/Semantic-UI#3692]
case: https://jsfiddle.net/3e5ygy25/

step to reproduce...
1. hover popup --> fine
2. click modal --> fine
3. close modal --> fine
4. hover popup --> weird

this behavior appear only when having fixed menu...

thank You...

**Comment by MeKarina** [comment]
after closing the modal,,, semantic leave body tag by having certain class and style,,,, by removing all of them `onHide` solve the issue...

see the fix...
https://jsfiddle.net/3e5ygy25/2/

**Comment by jlukic** [comment]
I've removed `position: relative` from `dimmable` when set to `body`, this should solve the change in `offsetContext` causing popups cached position to be invalidated.

**Comment by MeKarina** [comment]
nope this doesn't solve the issue... `<body class="dimmable">` still remain...

or maybe my mistake...
```less
/*******************************
    User Variable Overrides
*******************************/

.dimmable:not(.body) {
  position: @dimmablePosition;
}
```

```less
/*******************************
        User Overrides
*******************************/

.dimmable:not(.body) {
  position: @dimmablePosition;
}
```
