### ISSUE TITLE
[Segment] Add basic for segments

### ISSUE THREAD

**Issue by esargent** [Semantic-Org/Semantic-UI#3801]
Enhancement or Bugfix depending on how you look at it:

When you use a `basic segment` (because you don't want a border) inside a `horizontal segments` class, you still get the border because the `.ui.horizontal.segments > .segment` rule takes precedence. So I recommend adding a `basic.segments` definition to solve the problem and maintain the same expectation even if a `basic segment` is wrapped by a `segments` element of some type.

```LESS
/*-------------------
   Basic
--------------------*/`

.ui.basic.segments {
  background: @basicBackground;
  box-shadow: @basicBoxShadow;
  border: @basicBorder;
  border-radius: @basicBorderRadius;
}
```

usage example:

```HTML
<div style="background-color:black;"> <!-- because you can see the issue clearly -->
    <div class="ui basic horizontal segments"> 
        <!--  below basic will be overridden by .ui.horizontal.segments > .segment -->
        <div class="ui basic segment">some content</div> 
        <div class="ui basic compact segment">Free radicals are bad.</div>
    </div>
</div>
```

Adding as an issue vs pull  because I'm not a CSS expert and not clear this is the best way to fix or if it might have other side effects.

**Comment by kmd1970** [comment]
I second this! Had to create my own custom css.

```css
/* remove shadows from segment ouline, basic segment? */
.ui.no.shadow.segment {
 	box-shadow: none;
}
```
