### ISSUE TITLE
[Header] Please add "top aligned" .header .icon option

### ISSUE THREAD

**Issue by kmd1970** [Semantic-Org/Semantic-UI#3804]
The default vertical-alignment for an icon inside a header is only "middle". Can we add a "top aligned" option? I would like to see some icons sit at the very top. (Also, padding-top needs to be 0 in this case)

``` css
.ui.header[class*="top aligned"] .icon {
  vertical-align: top !important;
  padding-top:0 !important;
}
```
