### ISSUE TITLE
Add cursor : not-allowed to disabled items.

### ISSUE THREAD

**Issue by kmd1970** [Semantic-Org/Semantic-UI#3859]
Please add  cursor : not-allowed to disabled items.
```css
.disabled {
    cursor: not-allowed !important;
}
```
http://i.stack.imgur.com/0SEN8.png
