### ISSUE TITLE
Trouble with .ui.container margin 0em for left & right side (only mobile/tablet devices)

### ISSUE THREAD

**Issue by enjoyiacm** [Semantic-Org/Semantic-UI#3918]
Hello and thanks for super UI!

I have some trouble on mobile/tablet devices, after customize standard ``.ui.container`` margin.

If I set ``.ui.container`` to this (for mobile):

```css
@media only screen and (max-width: 767px) {
  .ui.container {
    margin-left: 0 !important;
    margin-right: 0 !important;
  }
}
```

I have space (~1em) only on right side and horizontal scroll (viewport is set to `width=device-width,initial-scale=1.0,maximum-scale=1.0`). Also, my `position: fixed` menu go to minus (~1em) margin to top. For more visuality, look this screen:

![trouble-ui-container-0-margin-left-right](https://cloud.githubusercontent.com/assets/11155743/14410449/c929af34-ff38-11e5-9bed-cd8c64635985.jpg)

This isn't `position: fixed` menu element (see CSS for it on screenshot), if I delete this — trouble still here. It's 'cause something wrong in `.ui.container` element. I think...

How to fix it? Why this happen? Help.
