### ISSUE TITLE
[Segment] Colored Segment Should Work in Segment Group

### ISSUE THREAD

**Issue by tubia** [Semantic-Org/Semantic-UI#4013]
Hi,
I'm trying to understand if it's possible to have a group of segments with one or more of them coloured.
Something like this:

``` html
<div class="ui segments">
    <div class="ui red segment"></div>
    <div class="ui segment"></div>
    <div class="ui segment"></div>
</div>
```

Currently, this rule override the border-top colour:

``` css
.ui.segments:not(.horizontal) > .segment:first-child {
border-top: none;
//...
}
```

Is this the expected result?

Thank you!
