### ISSUE TITLE
Site-wide box-sizing conflicts with custom CSS

### ISSUE THREAD

**Issue by tubia** [Semantic-Org/Semantic-UI#4035]
Hi all,
I'm using Semantic-UI inside a wide project of legacy software that uses its own CSS.
I'm experiencing a problem which seems related to `box-sizing` and in particular the definition of generic HTML elements in this set of CSS rules:
```css
html {
  box-sizing: border-box;
}
*, *::after, *::before {
    box-sizing: inherit; }
```
If I remove this rules, of course Semantic-UI doesn't work correctly, if I left them, other part of the website affected by my custom CSS totally fall apart.
Everything is with namespace except this part of CSS: is there something I'm missing?

**Comment by IonutBajescu** [comment]
I can't guarantee that this workaround will work, but is worth trying: 

```css
.ui {
  box-sizing: border-box;
}

*, *::after, *::before {
    box-sizing: inherit; 
}
```

**Comment by tubia** [comment]
Hi,
I see your reply only now.
I resolved namespacing html `box-sizing` with `ui` class:
```css
html .ui {
  box-sizing: border-box;
}
```
