### ISSUE TITLE
[Grid] - Column widths on grids with a non-default number of rows won't work

### ISSUE THREAD

**Issue by jcano** [Semantic-Org/Semantic-UI#4143]
I have the following code: https://jsfiddle.net/793yvu54/

``` html
<div class="ui three column grid">
  <div class="three wide column">
  </div>
  <div class="column">
  </div>
  <div class="column">
  </div>
  <div class="column">
  </div>
</div>
```

I would expect the first element to take the whole width of the grid, but it expands only 3 out of 16 columns. I can get the desired result either by using

``` html
<div class="ui three column grid">
  <div class="sixteen wide column">
  </div>

  [...]

</div>
```

or using rows

``` html
<div class="ui three column grid">
  <div class="one column row">
    <div class="column">
    </div>
  </div>

  [...]

</div>
```

but for subdivisions (a column stretching 2/3 of the width, for example) it's not possible to use any of these approaches.

I think this is due to the limitations of CSS, I cannot think of a way of achieving this behaviour without JS, but then again I'm not a CSS expert. Is there a way of achieving this behaviour with the default build?

**Comment by nix1** [comment]
I also find this to be a serious issue. It's doable in CSS, I suspect that one of the obstacles could be increasing the file size of grids even more.

BTW, I prepared a more straighforward example with 12 elements which I want to be flowing differently depending on device type: https://jsfiddle.net/fuLj3jss/1/

**Comment by JohannesLamberts** [comment]
I had the same problem with a `two wide column` in a `three wide grid`.
This fixed it for me:

```css
.ui.grid[class*="three column"] > .column:not(.row)[class*="two wide"],
.ui.grid[class*="three column"] > .row > .column[class*="two wide"]
{
  width: calc(100% / 3 * 2) !important;
}
```
