### ISSUE TITLE
[Label] - Display bugs with some icon patterns

### ISSUE THREAD

**Issue by pierre-weceipt** [Semantic-Org/Semantic-UI#4155]
When using floating labels, icons are displayed vertically and not horizontally.
http://jsfiddle.net/rduvhn8u/130/

Also when using just an icon in a circular label, the label is not perfectly circular
http://jsfiddle.net/fefqycbm/2/
For this one, Something like this seems to work
```css
.ui.label > .icon:only-child {
  margin: 0;
}
```
