### ISSUE TITLE
collections/grid: Menu item uses missing (old) font Neutraface instead of Open Sans

### ISSUE THREAD

**Issue by hastebrot** [Semantic-Org/Semantic-UI#43]
The font in the black menu items, The font Neutraface is not found and defaults to a serif font.

![collections_grid](https://f.cloud.github.com/assets/496255/1176744/1e5fb122-2171-11e3-93b3-71664e1ac16f.png)

``` css
#example .page .menu, 
#example .page .of {
  font-family: 'Neutraface';
}
```
