### ISSUE TITLE
[Divider] - Vertical dividers broken on documentation site

### ISSUE THREAD

**Issue by 1vasari** [Semantic-Org/Semantic-UI#4342]
The vertical dividers appear to just stick to the left side. See [this fiddle](http://jsfiddle.net/xox5kt31/1/) and screenshot below.

![sui bug](https://cloud.githubusercontent.com/assets/1539253/17159751/1a8873e8-53e3-11e6-9acf-40359dae37e6.png)

**Comment by ecehanece** [comment]
I am getting the same problem on my web projects. I think this code is occuring the error: 

.ui.grid > .column + .divider, .ui.grid > .row > .column + .divider {
    left: auto;
} 

I suppose if you disable this code sample, the error is going to be removed.

**Comment by llturro** [comment]
Happens since last update from Chrome. Firefox renders correct.

**Comment by jlukic** [comment]
Can confirm Chrome 51 looks fine and Chrome 52 looks bugged.

**Comment by jlukic** [comment]
I've posted a bug with Chromium. There does not appear to be a workaround from a framework level. Hopefully Chrome team can fix this soon.

https://bugs.chromium.org/p/chromium/issues/detail?id=633011&can=1&q=position%3A%20absolute%20flex&colspec=ID%20Pri%20M%20Stars%20ReleaseBlock%20Component%20Status%20Owner%20Summary%20OS%20Modified

**Comment by Sarke** [comment]
A simple workaround if anyone is having problems: http://jsfiddle.net/xox5kt31/2/

**Comment by timothycoutlakis** [comment]
This worked for me:

    .ui.grid>.column+.divider, .ui.grid>.row>.column+.divider {
        left: 50%;
    }

**Comment by Sarke** [comment]
That only works if you have exactly 2 columns.

**Comment by indiealexh** [comment]
Please note. This behaviour is correct to the spec and Edge works the same way. This will not be fixed by browsers.

**Comment by jlukic** [comment]
@indiealexh This is why the conversation is with spec makers.

**Comment by ciajulius** [comment]
I'm using Firefox developer edition (52.0a2, 64bit) on ubuntu and having the same problem with vertical divider

**Comment by allthesignals** [comment]
Updated @Sarke's fiddle to use https when pulling the css in his solution (not sure how to propose changes to your fiddle): http://jsfiddle.net/allthesignals/xox5kt31/7/

**Comment by Jano7z** [comment]
This thread was useful for me, but you can also check [propiedades del fenogreco](http://www.fenogrecoalholva.com/2016/11/propiedades-de-las-semillas-de-fenogreco-o-alholva.html)

**Comment by madela** [comment]
In older versions of Semantic this problem doesn't exist even with the latest Chrome versions. I think on version 2.2.2 it's rendered correctly

**Comment by samdoidge** [comment]
This issue is still happening, and all the fixes currently seem to render this as a horizontal divider - not vertical.

**Comment by Sarke** [comment]
@samdoidge The fix I posted above works.

**Comment by samdoidge** [comment]
@Sarke Apologies, it looks like it does. I was viewing in a smaller window where it defaults as a horizontal divider.

**Comment by amingilani** [comment]
Hey @jlukic

I appreciate all the work you've done with this framework. It's a joy to use and I'm sorry https://github.com/w3c/csswg-drafts/issues/401 rejected your proposal.

However, the behavior remains broken in the latest release and it's been so for almost 10 months now. Would it be possible to implement a workaround for the time being while the upstream bureaucracy plays out their drama?

**Comment by Bodacious** [comment]
Any update on this issue? We're using Semantic UI on a project that's about to go live and still seeing this issue on all browsers except Safari

**Comment by bubach** [comment]
The proposed fix is only for one divider, or two columns. The documentation page uses more. Looks like wrapping with relative position & padding/margin 0 solves it, like:
```<div style="position:relative; margin:0; padding:0;"><div class="ui vertical divider">Or</div></div>```

But it would look way nicer if the final solution could be structured as:
```<div class="ui vertical"><span class="divider">Or</span></div>``` or similar.

**Comment by renefs** [comment]
This problem also happens on Firefox 57

**Comment by Handymax** [comment]
Why not just manually set style attr  like: 
<div class="ui vertical divider" style="left:50%">Or</div>

**Comment by Handymax** [comment]
How about manually set style attr to the div, like:      

`<div class="ui vertical divider" style="left:50%"> Or</div>`

**Comment by kariyngva** [comment]
This workaround might be useful to someone, so long as they don't need dividers for more than five columns. It's not pretty but seems to work but I'm new to Semantic UI so this might not work as well as I think.

The ```.column``` selector can be replaced by the ```*``` selector. For more columns just repeat the pattern.

```CSS
.two .ui.vertical.divider {
  left: 50%;
}


.three {
  .ui.vertical.divider {
    left: 33%;
  }

  .ui.vertical.divider + .column + .ui.vertical.divider {
    left: 66%;
  }
}

.four {
  .ui.vertical.divider {
    left: 25%;
  }

  .ui.vertical.divider + .column + .ui.vertical.divider {
    left: 50%;
  }

  .ui.vertical.divider + .column + .ui.vertical.divider + .column + .ui.vertical.divider {
    left: 75%;
  }

  .ui.vertical.divider + .column + .ui.vertical.divider + .column + .ui.vertical.divider + .column + .ui.vertical.divider {
    left: 100%;
  }
}

.five {
  .ui.vertical.divider {
    left: 20%;
  }

  .ui.vertical.divider + .column + .ui.vertical.divider {
    left: 40%;
  }

  .ui.vertical.divider + .column + .ui.vertical.divider + .column + .ui.vertical.divider {
    left: 60%;
  }

  .ui.vertical.divider + .column + .ui.vertical.divider + .column + .ui.vertical.divider + .column + .ui.vertical.divider {
    left: 80%;
  }
}


@media screen and (min-width: (@tabletBreakpoint - 1px)) and (max-width : (@computerBreakpoint - 1px)) {
  .stackable.four,
  .stackable.three {
    .ui.vertical.divider {
      left: 50% !important;
    }
  }

  .stackable.five {
    .ui.vertical.divider {
      left: 34% !important;
    }

    .ui.vertical.divider + .column + .ui.vertical.divider + .column + .ui.vertical.divider + .column + .ui.vertical.divider {
      left: 67% !important;
    }
  }
}
```
