### ISSUE TITLE
collections/table: Celled table with 2px border on left side

### ISSUE THREAD

**Issue by hastebrot** [Semantic-Org/Semantic-UI#44]
Left border in the first column cells of the celled table adds 1px additionally to the 1px table border.

![collections_table](https://f.cloud.github.com/assets/496255/1176849/d935bed2-2172-11e3-825a-0e77993f0f2b.png)

``` css
.ui.celled.table tbody td {
  border: 1px solid #E0E0E0;
}
```
