### ISSUE TITLE
Revealing text content behind an image (Text wrapping issue)

### ISSUE THREAD

**Issue by qJake** [Semantic-Org/Semantic-UI#4482]
It appears that there is no built-in way to reveal an image with paragraph content underneath, particularly because of this definition:

```css
.ui.slide.reveal {
    /* ... */
    white-space: nowrap;
}
```

Which doesn't allow text in the reveal container to wrap.

I am proposing something such as this:

```html
<div class="ui slide reveal image">
    <img class="visible content" src="..." />
    <div class="hidden text content">
        This is a long paragraph of text that will wrap onto the next line, or maybe the line after it ...
    </div>
</div>
```

And the definition to complement it:

```css
.ui.slide.reveal > .text.content {
    white-space: normal;
    word-wrap: break-word;
}
```

Thoughts?
