### ISSUE TITLE
[Button] - Icon Button Group Should center icon inside button

### ISSUE THREAD

**Issue by Chris-R3** [Semantic-Org/Semantic-UI#4487]
icons inside an icon button group appear off-center

[example in button docs](http://semantic-ui.com/elements/button.html#icon-buttons)

the issue seems to be located here:

``` less
// src/definitions/elements/button.less:594
.ui.button:not(.icon) > .icon:not(.button):not(.dropdown) {
  margin: @iconMargin;
}
```
