### ISSUE TITLE
Content of the Grid is affected by Metas

### ISSUE THREAD

**Issue by mrkam** [Semantic-Org/Semantic-UI#4666]
**Steps to Reproduce**
1. Put a Grid inside a Card after a right floated Meta
2. See that it's right column is not where the card right side is

**Expected**
The Grid (red column) should be touching right side of the Card.

**Result**
The Grid does not do this

**Testcase**
http://jsfiddle.net/26wr5oru/4/

**Comment by Banandrew** [comment]
Hi @mrkam,

There’re many combinations of components, and I think that implementing every use case possible might be counterproductive, considering how easy it is to override the undesired behavior:
```CSS
.ui.card>.content>.meta+.ui.grid,
.ui.cards>.card>.content>.meta+.ui.grid {
  margin-top: .5em; // It’s most certainly a variable.
}
```
Which actually copies a card’s description rules:
```CSS
.ui.card>.content>.header+.description,
.ui.card>.content>.meta+.description,
.ui.cards>.card>.content>.header+.description,
.ui.cards>.card>.content>.meta+.description {
    margin-top: .5em; // It’s most certainly a variable.
}
```
