### ISSUE TITLE
[Breadcrumbs] - Line height might need to be a higher value

### ISSUE THREAD

**Issue by ivantcholakov** [Semantic-Org/Semantic-UI#4671]
http://jsfiddle.net/zjjm4ay7/1/

When browser screen is narrowed and the breadcrumb gets in two lines there is no enough vertical space between them.

I did this quick workaround in my place:

``` less
/*******************************
         Site Overrides
*******************************/

.ui.breadcrumb {
    line-height: 2;
    margin: (@verticalMargin / 2) 0em;
}
```

Before:
![before](https://cloud.githubusercontent.com/assets/1438104/19548724/e0917df2-96a8-11e6-80c6-2debe804d005.png)

After:
![after](https://cloud.githubusercontent.com/assets/1438104/19548746/fde06a9e-96a8-11e6-9634-ab16ce25ecd9.png)

Edit 23-OCT-2016: A snippet for testing:

``` less
                <div class="ui breadcrumb">

                    <a href="http://localhost/starter-public-edition-3-md/www/" class="section"><i class="fa fa-home"></i> Home</a>
                    <span class="divider">/</span>
                    <a href="http://localhost/starter-public-edition-3-md/www/playground" class="section"><i class="fa fa-sun-o"></i> The Palyground</a>
                    <span class="divider">/</span>
                    <a href="http://localhost/starter-public-edition-3-md/www/playground/datatables" class="section">DataTables</a>
                    <span class="divider">/</span>
                    <div class="active section">DataTables with Server-Side Processing</div>

                </div>
```
