### ISSUE TITLE
transition conflicts with class 'loading'?

### ISSUE THREAD

**Issue by GoodBoyCC** [Semantic-Org/Semantic-UI#4673]
i use class 'loading' to rotate a img, and than i want to use transition for some animation, but the img not rotate.

**Comment by Banandrew** [comment]
@jlukic 

There’s a conflict because of the rule below, I think it’s pretty self-explanatory, but please see [this fiddle](http://jsfiddle.net/Banandrew/o1wx3Lcd/).

```CSS
/* dist/components/transition.css */

/* Loading */
.loading.transition {
  position: absolute;
  top: -99999px;
  left: -99999px;
}
```
