### ISSUE TITLE
Higher dpi menu dividers

### ISSUE THREAD

**Issue by tsvetowntopalov** [Semantic-Org/Semantic-UI#4689]
Hey I am not sure if I am right, but isn't it better for the menu divider instead of using 

``` less
.ui.menu .item:before {
// ....
width: @dividerSize;
background:` @dividerBackground;
}
```

to go for 

``` less
.ui.menu .item:before {
// ....
border-right: @dividerSize solid @dividerBackground;
}
```

![demodpi](https://cloud.githubusercontent.com/assets/2925669/19697171/f8f0517c-9af2-11e6-9e5a-2fe412254d40.png)
