### ISSUE TITLE
Misaligned attached div in the examples

### ISSUE THREAD

**Issue by zerkms** [Semantic-Org/Semantic-UI#4698]
The most bottom example on the http://semantic-ui.com/examples/attached.html page has the top `div` misaligned to the table below.

Reproducible in chrome, edge, firefox.

![screenshot 2016-11-01 13 02 46](https://cloud.githubusercontent.com/assets/302295/19875678/a5ca8044-a033-11e6-836f-60cb8ecddd05.png)

**Comment by Banandrew** [comment]
It seems that `.ui.attached.table` is responsible:
```CSS
.ui.attached.table {
  margin: 0em @attachedHorizontalOffset;
  /* Equals to -@borderWidth that equals to 1px, or “-1px” */
}
```
