### ISSUE TITLE
Fixed menu hides following elements

### ISSUE THREAD

**Issue by brigand** [Semantic-Org/Semantic-UI#479]
If you have a fixed menu, it covers the following element.  Most people follow a menu with a grid, so if we put some padding on the top of the grid; it won't overlap.
- [testcase broken](http://jsfiddle.net/26Gu2/1/)
- [testcase working](http://jsfiddle.net/26Gu2/)

Something like this, but taking into account various menu sizes.  We have to use `rem` because grids have a font-size of 0, so any number of `em` would be `0px`.

``` css
.ui.fixed.menu + .ui.grid {
    padding-top: 3rem;
}
```
