### ISSUE TITLE
[Form] Variable length fields should have bottom margin in mobile mode

### ISSUE THREAD

**Issue by zxlin** [Semantic-Org/Semantic-UI#4876]
Variable length fields for forms do not have a bottom margin when the screen is in "mobile" width (under 767px).

See JS Fiddle: http://jsfiddle.net/109msfpr/1/

Or following screenshots:

|Desktop|Mobile|
|---|---|
|<img width="848" alt="screen shot 2017-01-01 at 4 47 54 pm" src="https://cloud.githubusercontent.com/assets/5447705/21583164/05ce6dd2-d042-11e6-834b-f4c2c04ba9f4.png">|<img width="459" alt="screen shot 2017-01-01 at 4 48 03 pm" src="https://cloud.githubusercontent.com/assets/5447705/21583165/087f9844-d042-11e6-9da8-daf8c1b9e2fe.png">|

**Comment by zxlin** [comment]
If I am not mistaken, something like the following should resolve it:

```CSS
@media
only screen and (max-width:767px) {
  .ui.form > .fields > .field[class*="wide"] {
    margin-bottom: 1em;
  }
}
```

Someone more knowledgable, please advise.
