### ISSUE TITLE
Icons are not aligned correctly

### ISSUE THREAD

**Issue by romaninsh** [Semantic-Org/Semantic-UI#4879]
Looking at this page, last example: http://semantic-ui.com/elements/button.html

Icons does not appear to be aligned correctly:

<img width="199" alt="screen shot 2017-01-03 at 10 00 04" src="https://cloud.githubusercontent.com/assets/453929/21609131/8bed0c1c-d1b8-11e6-8675-7b0980e964cd.png">

After mentioning it on [Gitter](https://gitter.im/Semantic-Org/Semantic-UI?at=586b7622aa6be0472fff397f), @Banandrew has recommended to report it here.

> @romaninsh you’re right, haven’t noticed it before. I think you found a bug, because the rule for icon buttons looks like this:
```LESS
.ui.icon.buttons .button > .icon,
.ui.icon.button > .icon {
  opacity: @iconButtonOpacity;
  margin: 0em;
  vertical-align: top;
}
```
But its margin gets overwritten with this rule that needs to be expanded/overwritten to include the grouped variation:
```LESS
.ui.button:not(.icon) > .icon:not(.button):not(.dropdown) {
  margin: @iconMargin;
}
```
If you need a temporary workaround, you can remove the `.icon` class from the container, and apply it to every child element to make it work again:
```HTML
<div class="ui small basic buttons">
  <button class="ui icon button"><i class="file icon"></i></button>
  <button class="ui icon button"><i class="save icon"></i></button>
  <button class="ui icon button"><i class="upload icon"></i></button>
  <button class="ui icon button"><i class="download icon"></i></button>
</div>
```
