### ISSUE TITLE
Change border color of dropdowns in forms?

### ISSUE THREAD

**Issue by Pithikos** [Semantic-Org/Semantic-UI#4942]
For the love of it, I have been fighting with SemanticUI for days now and it has halted all further development for my website. I have a form with several different UI elements that when highlighted, have a blue border. I want to change that but can't figure out how.

![Screenshot](https://s28.postimg.org/q9mcnxpnh/Screenshot_from_2017_01_26_09_07_15.png)

I have tried a myriad of different things in the `site.variables` but nothing seems to work.

Some of the things tried:

```css
..
@borderColor: @red;
@solidBorderColor: @red;
@internalBorderColor: @red;
@selectedBorderColor: @red;
@inputfieldActiveBorder: @red;
@inputActiveBorder: @green;
@fieldActiveBorder: @yellow;
@selectedBorderColor: @pink;
@activeBorderColor: @orange;
@labelHoverBackgroundColor: @green;
@labelActiveBackgroundColor: @pink;
@labelActiveBorder: @red;
@downBorderColor: @primaryColor;
@downBackground: @red;
@downColor: @yellow;
..
```

Is this even possible? This is a huge problem for me because blue simply doesn't fit the rest of my palette and although I like SemanticUI I have started to despise it merely for this little annoyance when it comes to customization.

Notice this happens when using `$('.ui.dropdown').dropdown();`. I am not sure if this has any impact.

**Comment by Pithikos** [comment]
A workaround is to override everything but it feels rather hacky and there is a latency in switching from the default blue to the designated color..

```css
input:active, input:focus,
textarea:active, textarea:focus,
select:active, select:focus,
.ui.dropdown:active, .ui.dropdown:focus, .ui.dropdown.active,
.ui .menu.visible {
   border-color: @primaryColor !important;
}
```
