### ISSUE TITLE
Unfit for modern web development using Web Components?

### ISSUE THREAD

**Issue by tbranyen** [Semantic-Org/Semantic-UI#4963]
I understand that as an early adopter using technology like Web Components, I cannot expect the existing tooling I'm accustomed to, to "just work".  Although in the case of Semantic UI, I'm worried that it's current design decisions do not align with the future of isolation and custom elements in the web via Web Components.

Example: You are building a data grid and want to separate the table from the row via components. So you have the following two components:

- TableComponent
- TableRowComponent

Once rendered the DOM Tree looks something like:

``` pre
~ TableComponent ~
  -> Shadow Root
    -> slot (table)
  -> table
      -> thead
      -> tbody
        -> ~ TableRowComponent (Subclasses TR) ~
          -> Shadow Root
            -> td
            -> td
```

The problem may not be immediately obvious, but as styles do not cross the shadow boundary and the way that Semantic UI forfeits explicit class names for element names, means that it's pretty much impossible to get this to work:

``` css
/* .ui.celled.table is styled perfectly, but there's no way to cascade into the td */
.ui.celled.table tr td, .ui.celled.table tr th {
    border-left: 1px solid rgba(34,36,38,.1);
}
```

How can we get these styles into the Shadow Root?

- CSS Variables? (Not really, they won't substitute full blocks, could help with theming)
- Flat class names? (Good solution, but [3671](https://github.com/Semantic-Org/Semantic-UI/issues/3671) didn't fair well...)
- JavaScript? (Really hope not)

Does the project/community have thoughts on this fundamental design problem?
