### ISSUE TITLE
Compact secondary menu border radius issue

### ISSUE THREAD

**Issue by maisoui** [Semantic-Org/Semantic-UI#5025]
Hi,

The border radius of the last item of a compact **secondary** menu is wrong.
![image](https://cloud.githubusercontent.com/assets/9716075/23014796/bc34825c-f430-11e6-8036-cbee690682d6.png)

The top/bottom left border radius are set to 0 by the rules:
```css
.ui.compact.menu .item:last-child {
	border-radius: 0 .28571429rem .28571429rem 0;
}
```

I think this rule should be modified to except **secondary** menu.

Best regards
