### ISSUE TITLE
[Menu] Inconsitency with inverted menu

### ISSUE THREAD

**Issue by RAI-AGH** [Semantic-Org/Semantic-UI#5083]
The left border of the first child of an inverted menu is set to the color of the border for a non-inverted menu.

Here's a proposed solution that overrides the color for inverted menu's to use the inverted border color:
```css
.ui.inverted.menu:not(.secondary):not(.text):not(.tabular):not(.borderless)>.container>.item:not(.right):not(.borderless):first-child {
    border-left: 1px solid rgba(255,255,255,.08);
}
```
