### ISSUE TITLE
Dropdown input search wrong size

### ISSUE THREAD

**Issue by RigobertoFelix** [Semantic-Org/Semantic-UI#5085]
Placing an ui search input inside a dropdown in a form gets a wrong size.

![image](https://cloud.githubusercontent.com/assets/11526005/23325078/acce90ac-faaf-11e6-880e-fe76163c5caf.png)

**Comment by Banandrew** [comment]
Hi, please provide a test case as per our [contributing guidelines](https://github.com/Semantic-Org/Semantic-UI/blob/master/CONTRIBUTING.md); you can fork [this JSFiddle](http://jsfiddle.net/efp8z6Ln).

**Comment by RigobertoFelix** [comment]
Here is an example in jsfiddle http://jsfiddle.net/o364q86L/

**Comment by Banandrew** [comment]
It seems that `.ui.form .field .ui.input`’s width overrides `.ui.dropdown .menu > .input`’width.

**Comment by RigobertoFelix** [comment]
i'm in love of semantic ui, if there's anything that i can help in the future I would do it with pleasure, by the way is there any way to fix it quickly?

**Comment by Banandrew** [comment]
@RigobertoFelix Sure, it’s very easy; open `installation_folder/src/site/modules/dropdown.overrides`, put the following there, then rebuild the framework:
```LESS
.ui.dropdown .menu > .input {
  width: auto !important;
  display: flex;
  margin: @menuInputMargin;
  min-width: @menuInputMinWidth;
}
```
