### ISSUE TITLE
Changing Icons For Dropdown Modules

### ISSUE THREAD

**Issue by callen5914** [Semantic-Org/Semantic-UI#5104]
Is it possible to switch the icon for the dropdowns to chevron down?

I looked at the setting for selector and tried to make changes there but I get an error which breaks the UI down.

>unrecognized expression: &gt; .dropdown.icon 

I tried using `icon : '&gt; .chevron.down.icon' ` for example and can't seem to get it.

Any ideas?

**Comment by kmd1970** [comment]
You could add this css to your page or layout
```css
.ui.dropdown > .dropdown.icon::before {
   font-family: 'Icons';
   content: "\f063" !important;
}
```
