### ISSUE TITLE
[Dimmer] color and overflow issues

### ISSUE THREAD

**Issue by niksajanjic** [Semantic-Org/Semantic-UI#5169]
Hi, just want to point out 2 potential issues I have with dimmer:

1) If you use inverted dimmer, color of the content is still white instead of being inverted too (being black):
```html
<div class="ui blurring segment dimmable dimmed">
  <div class="ui dimmer inverted transition visible active">
    <div class="content">
      <div class="center">
        <p>Lorem ipusus...</p>
      </div>
    </div>
  </div>
  <img class="ui wireframe image" src="/images/wireframe/short-paragraph.png">
  <img class="ui wireframe image" src="/images/wireframe/short-paragraph.png">
</div>
```
In this case color of the **p** tag is white same as it is if dimmer isn't inverted. Because inverted dimmer has white background it's content text is invisible. Dimmer's has this rule for it's content:
```css
.ui.dimmer>.content>* {
  display: table-cell;
  vertical-align: middle;
  color: #fff;
}
```
which sounds correct if dimmer isn't inverted. In our case we also added inverted class to our dimmer which adds this rule:
```css
.ui.inverted.dimmer>.content>* {
    color: #fff;
}
```
But this rule doesn't seem to be right. Shouldn't it be inverted color (blackish). After looking at file _/src/definitions/modules/dimmer.less_ on line 152 we have these rules:
```less
.ui.inverted.dimmer {
  background-color: @invertedBackgroundColor;
}
.ui.inverted.dimmer > .content > * {
  color: @textColor;
}
```
but after looking at file _/src/themes/default/modules/dimmer.variables_ on line 52 we have these rules:
```less
/* Inverted */
@invertedBackgroundColor: rgba(255, 255, 255, 0.85);
@invertedTextColor: @textColor;
```
where @textColor is `@white`. To me it seems here is where the problem lies.

2) Dimmer content isn't scrollable. According to docs we should always put content inside .content .center classes so we can be sure it's getting centered. Sometimes that content is going to be dynamically inserted and we can't be sure if that content is going to be vertically longer than the space we have provided by dimmer. In that case we added custom class that adds rule:
```css
.scrollable-dimmer {
  overflow-y: auto;
}
```
But it seems to me this can be added automatically inside this rule:
```css
.dimmed.dimmable>.ui.animating.dimmer, .dimmed.dimmable>.ui.visible.dimmer, .ui.active.dimmer {
    display: block;
    opacity: 1;
    overflow-y: auto; /* add this rule */
}
```
This should allow every dimmer to have scrollable content if needed.
