### ISSUE TITLE
Grid inconsistent margins on small screens

### ISSUE THREAD

**Issue by yamsellem** [Semantic-Org/Semantic-UI#5170]
Grid and stackable grids don't seems to have the same behavior on small screens:

```css
@media only screen and (max-width: 767px) {
    .ui.grid {
        margin-left: -1rem !important;
        margin-right: -1rem !important;
    }
    .ui.stackable.grid {
        margin-left: 0rem !important;
        margin-right: 0rem !important;
    }
}
```

To mixed `.ui.grid` and `.ui.stackable.grid` on the same page I have to fix this in `grid.overrides`:

```css
@media only screen and (max-width: 767px) {
    .ui.grid {
        margin-left: 0rem !important;
        margin-right: 0rem !important;
    }
}
```

Have I missed something?

**Comment by Banandrew** [comment]
I wonder why this was done, seems to be a purely aesthetic choice.

**Comment by hugopeek** [comment]
You're not missing anything, I keep bumping into this one too. I ended up with the following fix, similar to yours:

```less
.ui.grid.container > .column,
.ui.container .grid:not(.nested) > .column {
    @media only screen and (max-width: @largestMobileScreen) {
        padding-left: 0 !important;
        padding-right: 0 !important;

        // Nested stackable grids are negatively affected by this change
        .ui.stackable.grid {
            margin-left: 0 !important;
            margin-right: 0 !important;
        }
    }
}
```

It's far from ideal, because it requires a custom `.nested` class to be assigned to all nested grids. I'm running into problems now because that class is not present in some scenarios, so I'm looking for a better fix.

Also, adding `.relaxed` classes to the affected grids will probably mess with this fix.

This issue seems to be related too: #4129
