### ISSUE TITLE
label not in the right position

### ISSUE THREAD

**Issue by rohitdesigner** [Semantic-Org/Semantic-UI#5172]
![capture](https://cloud.githubusercontent.com/assets/17812216/23957865/c1a35b7e-0933-11e7-8f30-ebd1cd90ed42.JPG)

CSS:
```css
body {
    display: flex!important;
    justify - content: center;
}

#w {
    align - self: center;
}
```
HTML:
```html
<div class="ui buttons" id="w">
  <div class="ui compact button">
    Home
  </div>
  <div class="ui button compact">
    class
    <div class="floating ui red label">22</div>
  </div>
</div>
```
