### ISSUE TITLE
Multiple .visible classes on same selector

### ISSUE THREAD

**Issue by cusspvz** [Semantic-Org/Semantic-UI#5192]
I was diggin' on `semantic-ui-2.2.9` until I've found a selector statement with multiple `.visible` class selectors on the same element.

```css

/*******************************
            States
*******************************/

/*--------------
    Visible
---------------*/

.ui.visible.visible.visible.visible.message {
  display: block;
}

.ui.icon.visible.visible.visible.visible.message {
  display: -webkit-box;
  display: -ms-flexbox;
  display: flex;
}
```

Tried to search for issues before posting, but didn't found. Sorry if it is duplicated.
