### ISSUE TITLE
right item in menu is missing when inside a pusher element

### ISSUE THREAD

**Issue by keelii** [Semantic-Org/Semantic-UI#5193]
I found this issue in my project, It seem that caused by `transform`

```css
.ui.visible.left.sidebar~.fixed, .ui.visible.left.sidebar~.pusher {
    -webkit-transform: translate3d(260px,0,0);
    transform: translate3d(260px,0,0);
}
```
DEMO:

http://codepen.io/keelii/pen/wJjRKW
