### ISSUE TITLE
[Message] Floating message does not work with any other modifier

### ISSUE THREAD

**Issue by komirad** [Semantic-Org/Semantic-UI#5222]
For example, one cannot float a info message. I don't see any documentation that says it shouldn't.

http://jsfiddle.net/sh4yegu0/1/

**Comment by EnriqueVidal** [comment]
I have the same problem, Messages don't float on top of content, has anybody found a fix for this?

**Comment by EnriqueVidal** [comment]
This is how I fixed it, the solution was to put all the messages under a new container and style it to be fixed on top of everything else. I looked for the break points in Semantic-UI's css and then just styled the container `<div class="messages" />` with this:

```css
/*******************************
      Messages Container
*******************************/

/* All Sizes */

.messages {
  left: 50%;
  margin-left: -48%;
  position: fixed;
  top: 45px;
  width: 96%;
  z-index: 100;
}

/* Tablet */

@media only screen and (min-width: 768px) and (max-width: 991px) {
  .messages {
    margin-left: -361.5px;
    width: 723px;
  }
}

/* Small Monitor */

@media only screen and (min-width: 992px) and (max-width: 1199px) {
  .messages {
    margin-left: -466.5px;
    width: 933px;
  }
}

/* Large Monitor */

@media only screen and (min-width: 1200px) {
  .messages {
    margin-left: -563.5px;
    width: 1127px;
  }
}
```

it seems to work in Mobile and Tablet too, [here](https://jsfiddle.net/ukk729ah/)'s a jsfiddle, one gotcha I need to point out is I set `top: 45px` on `.messages` to not make the menu inaccessible, but you can tweak that out to match your site. Hope this helps.
