### ISSUE TITLE
Tables shrinking too soon

### ISSUE THREAD

**Issue by IsaakGroepT** [Semantic-Org/Semantic-UI#5233]
I'm using the latest Firefox and noticed that the tables, take for example the collapsing one, resize too soon into mobile compatible one (as a result of responsive design).

For example:
I have a 300px width and 200px height collapsing table, that shrinks when the browser width is reduced to 760px, even though there is still plenty of space left for the table. That resizing behaviour is preferable, but that's too soon for PC browsers and messes up the layout easily. I tried looking up a solution or hacking the style with min-width and other stuff, but with no good result.

I noticed it also happens to the demos at: https://semantic-ui.com/collections/table.html

**Comment by Banandrew** [comment]
Hi @IsaakGroepT, the behaviour is intended, and I don’t think we can do something about it, because it’s impossible to know the size of a `.collapsing` table beforehand. What you could do is add `.unstackable` to the table to turn off [the default media-queries](https://github.com/Semantic-Org/Semantic-UI/blob/master/src/definitions/collections/table.less#L151), and add the following to `installation_folder/src/site/collections/table.overrides`; don’t forget to rebuild the framework afterwards:
```LESS
/* Use whatever max-width you’re comfortable with. I used your GitHub username to namespace it. */
@media only screen and (max-width : 399px) {
  .ui.table.IsaakGroepT {
    width: 100%;
  }
  .ui.table.IsaakGroepT tbody,
  .ui.table.IsaakGroepT tr,
  .ui.table.IsaakGroepT tr > th,
  .ui.table.IsaakGroepT tr > td  {
    display: block !important;
    width: auto !important;
    display: block !important;
  }

  .ui.table.IsaakGroepT {
    padding: 0em;
  }
  .ui.table.IsaakGroepT thead {
    display: @responsiveHeaderDisplay;
  }
  .ui.table.IsaakGroepT tfoot {
    display: @responsiveFooterDisplay;
  }
  .ui.table.IsaakGroepT tr {
    padding-top: @responsiveRowVerticalPadding;
    padding-bottom: @responsiveRowVerticalPadding;
    box-shadow: @responsiveRowBoxShadow;
  }

  .ui.table.IsaakGroepT tr > th,
  .ui.table.IsaakGroepT tr > td {
    background: none;
    border: none !important;
    padding: @responsiveCellVerticalPadding @responsiveCellHorizontalPadding !important;
    box-shadow: @responsiveCellBoxShadow;
  }
  .ui.table.IsaakGroepT th:first-child,
  .ui.table.IsaakGroepT td:first-child {
    font-weight: bold;
  }
}
```
Thank you for posting, but although it’s a valid usage question, we’ve limited GitHub Issues to bug reports and feature requests, keeping the board more manageable for maintainers; see the [contributing guidelines](https://github.com/Semantic-Org/Semantic-UI/blob/master/CONTRIBUTING.md) for more information on what kind of posts should find themselves into the GitHub Issues board.

Here’s a list of our other support resources:
* [Gitter chatroom](https://gitter.im/Semantic-Org/Semantic-UI)
* [Official forums](http://forums.semantic-ui.com)
* [StackOverflow](http://stackoverflow.com/questions/tagged/semantic-ui)
