### ISSUE TITLE
List .content inside accordion gets additional padding

### ISSUE THREAD

**Issue by pierre-weceipt** [Semantic-Org/Semantic-UI#5238]
Hi, similar issue as #803, when using list Inside accordions the content gets extra padding from accordions css when theres no icon before content. here is the jsfiddle http://jsfiddle.net/ugwwf022/2/ and the impacting css : 

```css
.ui.styled.accordion .content, .ui.styled.accordion .accordion .content {
   margin: 0em;
   padding: 0.5em 1em 1.5em;
}
```
