### ISSUE TITLE
[Button][Enhancement] Allowing single button attached "buttons" group

### ISSUE THREAD

**Issue by shanehsu** [Semantic-Org/Semantic-UI#5251]
As of now (tested in 2.2.10 and 2.2.2), the `ui bottom attached buttons` doesn't behave well with one button as its child. While using `ui bottom attached button` would be good enough, my Angular application would have been a lot more complicated this way.

Suggestions:
The [current code](https://github.com/Semantic-Org/Semantic-UI/blob/master/src/definitions/elements/button.less#L1062) in `bottom attached` section:
```less
.ui[class*="bottom attached"].buttons {
  margin-top: @attachedOffset;
  border-radius: 0em 0em @borderRadius @borderRadius;
}
.ui[class*="bottom attached"].buttons .button:first-child {
  border-radius: 0em 0em 0em @borderRadius;
}
.ui[class*="bottom attached"].buttons .button:last-child {
  border-radius: 0em 0em @borderRadius 0em;
}
```

Change to:
```less
.ui[class*="bottom attached"].buttons {
  margin-top: @attachedOffset;
  border-radius: 0em 0em @borderRadius @borderRadius;
}
.ui[class*="bottom attached"].buttons .button:only-child {
  border-radius: 0em 0em @borderRadius @borderRadius;
}
.ui[class*="bottom attached"].buttons .button:first-child {
  border-radius: 0em 0em 0em @borderRadius;
}
.ui[class*="bottom attached"].buttons .button:last-child {
  border-radius: 0em 0em @borderRadius 0em;
}
```

> The other three `attached` section will need this change as well if suggestion is accepted.

My knowledge of Semantic UI and LESS is not good enough for a PR, but this requires discussion anyway.
