### ISSUE TITLE
[Tab] Centered Tab

### ISSUE THREAD

**Issue by rafalradomski** [Semantic-Org/Semantic-UI#5589]
Be default all tabs are on the left: https://semantic-ui.com/modules/tab.html

How I can achieve centered Tab like in [Bootstrap 4](https://v4-alpha.getbootstrap.com/components/navs/#horizontal-alignment) ?

 There is no example of centered tab in Semantic doc

**Comment by Banandrew** [comment]
Hi @rafalradomski, it doesn’t exist. Would you like to request it?

**Comment by rafalradomski** [comment]
@Banandrew I surprised no one asks about it before, it's common use case on centered pages

**Comment by Atulin** [comment]
I'd rather it doesn't disappear in a pile of stale issues, so here's some activity from me: I'd also like to have a way to have my tabs centered.

**Comment by franckpopchef** [comment]
Just ran in the same issue. Would be great if it is implemented.

**Comment by franckpopchef** [comment]
Quick CSS fix:
Add margin-left: auto to the first child of the menu and margin-right: auto to the last child.

Example:
```css
.ui.secondary.pointing.menu a:first-child {
  margin-left: auto;
}

.ui.secondary.pointing.menu a:last-child {
  margin-right: auto;
}
```

Result:
![Image of SUI Tabs Centered](https://i.imgur.com/5SmTuU3.png)
