### ISSUE TITLE
[DROPDOWN] Lock icon missing on disabled dropdown

### ISSUE THREAD

**Issue by smartm0use** [Semantic-Org/Semantic-UI#5598]
If I want to disable a selection dropdown, how to add a lock icon such as we do with input text?

Here is my code: https://jsfiddle.net/gc0b8qxh

I have tried the following way, but I can't figure out why it doesn't work:

https://jsfiddle.net/8vm1c25f

Could this be a feature request or issue?

**Comment by Banandrew** [comment]
Hi @smartm0use, I’m not sure why `content` overriding doesn’t work, and I think you’ll have to temporarily add the `.lock` icon similarly to the `.dropdown.icon` to `src/site/modules/dropdown.overrides`; depending on what dropdown variations you need—if I didn’t miss anything—something like this:
```CSS
.ui.disabled.dropdown > .lock.icon {
  position: relative;
  width: auto;
  font-size: @dropdownIconSize;
  margin: @dropdownIconMargin;
}
.ui.disabled.selection.dropdown > .lock.icon {
  cursor: pointer;
  position: absolute;
  width: auto;
  height: auto;
  line-height: @searchSelectionLineHeight;
  top: @selectionVerticalPadding;
  right: @selectionHorizontalPadding;
  z-index: @selectionIconZIndex;
  margin: @selectionIconMargin;
  padding: @selectionIconPadding;
  opacity: @selectionIconOpacity;
  transition: @selectionIconTransition;
}
```
There’re also a couple of rules for other dropdown variations if you need them. Marking the issue as enhancement.
