### ISSUE TITLE
[Dropdown] tamanho sub item

### ISSUE THREAD

**Issue by WallaceMielniczki** [Semantic-Org/Semantic-UI#5657]
http://jsfiddle.net/ca0rovs3/62/ icone do dropdown em cima do texto

**Comment by WallaceMielniczki** [comment]
demora muito para vocês resolverem esse bug como funciona?

**Comment by Banandrew** [comment]
@WallaceMielniczki 
```CSS
.ui.vertical.menu .dropdown.item .menu {
  min-width: -webkit-max-content;
  min-width: -moz-max-content;
  min-width: max-content;
}
```
