### ISSUE TITLE
[Image] table and image not working

### ISSUE THREAD

**Issue by abolfazl-ziaratban** [Semantic-Org/Semantic-UI#5781]
semantic ui version : 2.2.13

image tag not working in table tag.
the bug is here(semantic.css:23889)
```css
.ui.table td .image img {
    max-width: none;
}
```

see https://jsfiddle.net/vnmgt6y9/6/
