### ISSUE TITLE
Modal close icon displays with incorrect color in basic fullscreen mode

### ISSUE THREAD

**Issue by lbssousa** [Semantic-Org/Semantic-UI#5831]
With latest Semantic-UI CSS, the close icon of a fullscreen modal is always displayed in black, regardless the modal is basic or not. For basic fullscreen modals with default dimmer, the close icon is almost invisible.

See an example: https://jsfiddle.net/xhrzhygk/

A simple CSS addition like this could fix the problem:
```css
.ui.basic.fullscreen.modal>.close {
  color: #fff;
}
```
