### ISSUE TITLE
.buttons and .button color overrides

### ISSUE THREAD

**Issue by brigand** [Semantic-Org/Semantic-UI#591]
Example HTML:

``` html
<div class="three blue ui buttons">
    <div class="ui button">A</div>
    <div class="green ui button">B</div>
    <div class="ui button">C</div>
</div>
```

It causes a problem because we declare our selectors like this:

``` css
.ui.blue.buttons .button, .ui.blue.button {
    background-color: blue;
}

.ui.green.buttons .button, .ui.green.button {
    background-color: green;
}
```

Which means that some colors will always have president over other colors.  We need to have all of the `.ui.{{color}}.buttons .button` selectors; then all of the single colored button selectors.

[demo](http://jsfiddle.net/2MrhH/)
