### ISSUE TITLE
Readonly plain text form field

### ISSUE THREAD

**Issue by corydeppen** [Semantic-Org/Semantic-UI#5990]
I've looked through the docs but haven't seen an equivalent to Bootstrap's [readonly plain text styling](http://getbootstrap.com/docs/4.0/components/forms/#readonly-plain-text) for form fields. This would be beneficial for those times when you'd rather not render a form input but prefer to only show the field label and value.

**Comment by dinhani** [comment]
I have the same issue. In forms where inputs and plain text are mixed, plain text fields seems out of place.

**Comment by prudho** [comment]
It's something that can be implemented like this:

In the file src/definitions/collections/form.less add the following lines:
```less
/*--------------------
   Plain-text fields
---------------------*/
.ui.form textarea.plain-text,
.ui.form input:not([type]).plain-text,
.ui.form input[type="date"].plain-text,
.ui.form input[type="datetime-local"].plain-text,
.ui.form input[type="email"].plain-text,
.ui.form input[type="number"].plain-text,
.ui.form input[type="password"].plain-text,
.ui.form input[type="search"].plain-text,
.ui.form input[type="tel"].plain-text,
.ui.form input[type="time"].plain-text,
.ui.form input[type="text"].plain-text,
.ui.form input[type="file"].plain-text,
.ui.form input[type="url"].plain-text {
  border-color: transparent !important;
  background-color: transparent !important;
  padding-left: 0em !important;
  padding-right: 0em !important;
  box-shadow: none !important;
  border-radius: 0px !important;
}
```
Then rebuild semantic-ui.

Just add the class `plain-text` to your form input (or textarea) and you'll see this result:
![result](http://i65.tinypic.com/2h4z7mx.png)
