### ISSUE TITLE
Invalid divider position

### ISSUE THREAD

**Issue by sackery** [Semantic-Org/Semantic-UI#6133]
The vertical divider not center between two element but left floated.

**Comment by sackery** [comment]
I just tweek that with:
```css
.ui.grid > .column + .divider,
.ui.grid > .row > .column + .divider {
  left: 50% !important;
}
```
