### ISSUE TITLE
[Icon] 'exchange alternate' icon is incorrect

### ISSUE THREAD

**Issue by iHaPBoy** [Semantic-Org/Semantic-UI#6212]
### [Icon] 'exchange alternate' icon is incorrect

The 'exchange alternate' icon is correct in document, but the sources is incorrect.

### Steps

**Icon Document:**

https://semantic-ui.com/elements/icon.html#arrows

'exchange alternate' is _correct_: `content: "\f699"`

**Sources:**

https://github.com/Semantic-Org/Semantic-UI/blob/master/src/themes/default/elements/icon.overrides#L106

'exchange alternate' is _incorrect_: `content: "\f362"`

### Expected Result
```css
i.icon.exchange.alternate:before { content: "\f699"; }
```

### Actual Result
```css
i.icon.exchange.alternate:before { content: "\f362"; }
```

### Version
2.3.0
