### ISSUE TITLE
Transition in (ordered) list

### ISSUE THREAD

**Issue by DiederikvandenB** [Semantic-Org/Semantic-UI#635]
Hey all!

I came across this little bug:
When you try to make a list item (.ui.ordered.list > .item) disappear through the transition class it fails, since the display: none is overridden by the .ui.list > .item which gives the class a display: list-item.

I fixed it by doing a

``` css
.ui.hidden.transition {
        display: none !important;
}
```

But I am not sure whether that is the appropriate fix though...
Anyway, thanks for making this awesome UI!
