### ISSUE TITLE
Forgo use of !important

### ISSUE THREAD

**Issue by supernintendo** [Semantic-Org/Semantic-UI#6384]
### Steps
Use any CSS rules that use `!important`, such as `.ui.text.container`.

### Expected Result
`!important` is not used.

### Actual Result
`!important` is used.

### Version
2.3.1

### Additional notes
The use of `!important` is lazy and problematic. It arbitrarily locks users of Semantic UI into its own theming paradigm rather than giving users the freedom to extend the CSS provided by the library with custom rules. Semantic UI developers should opt for scoped CSS rules that are strict enough to override defaults yet easily extended (for example, `html.semantic body`) rather than brute forcing CSS by way of `!important`.

**Comment by em** [comment]
Agreed. See https://github.com/Semantic-Org/Semantic-UI/issues/280

**Comment by avinashdvv** [comment]
what happens if i remove !important from the css.

**Comment by davegson** [comment]
totally agree, it's giving me headaches to implement small, custom changes...

**Comment by davegson** [comment]
I feel this way to write custom css is rather problematic:

```css
.custom-class {
  background-color: #eee !important;
  padding-top: 50px !important;
  border-bottom: 1px solid #ccc !important;
}
```

It leads to everything having to be `!important` leading to _nothing_ being important.
