### ISSUE TITLE
[List] items in a selection list should display their active state

### ISSUE THREAD

**Issue by Neketch** [Semantic-Org/Semantic-UI#6436]
### Description
Items in a list with "selection" class never display their active state, only the hover one.

### Solution
My guess is a space is missing between selectors, which adds more specifity weight for the hover state.
https://github.com/semantic-org/semantic-ui/blob/master/src/definitions/elements/list.less#L474 :
```css
.ui.selection.list.list > .item:hover
``` 

should be

```css
.ui.selection.list .list > .item:hover
``` 

just like the `active` state below :
```css
.ui.selection.list .list > .item:active,
.ui.selection.list > .item:active {
  background: @selectionListDownBackground;
  color: @selectionListDownColor;
}
```

### Result
![selection list](https://user-images.githubusercontent.com/20594122/41468790-6765d494-70ab-11e8-85db-563bcf69477d.gif)
