### ISSUE TITLE
menu: using capitalized 'LEFT' to denote icon position

### ISSUE THREAD

**Issue by MohammadYounes** [Semantic-Org/Semantic-UI#657]
By default vertical menu icons are right aligned, but I wanted to have the opposite:

![left side icons](https://f.cloud.github.com/assets/4712046/2240521/f3e3556e-9c97-11e3-8ec3-52f0ab0c9714.PNG)

My [first attempt](http://jsfiddle.net/r38eh/) was to exclude `.left` icons from the [rule](https://github.com/Semantic-Org/Semantic-UI/blob/master/src/collections/menu.less#L518):

``` CSS
.ui.vertical.menu .item > i.icon:not(.left) {
  float: right;
  width: 1.22em;
  margin: 0em 0em 0em 0.5em;
}
```

![left right icons attempt 1](https://f.cloud.github.com/assets/4712046/2240539/f103e046-9c99-11e3-9656-1a0958117e2f.PNG)

It worked for `i.settings.icon`, but not for `i.basic.icon.chart`,  because `i.basic.icon.left` ([left arrow](https://github.com/Semantic-Org/Semantic-UI/blob/master/src/elements/basic.icon.less#L81)) is listed after the [chart](https://github.com/Semantic-Org/Semantic-UI/blob/master/src/elements/basic.icon.less#L68) in [basic.icon.css](https://github.com/Semantic-Org/Semantic-UI/blob/master/src/elements/basic.icon.less).

So I thought about changing the order of icon classes, making all directional icons appear first, but this approach will fail in the case of a `.left` directional icon that needs to be placed to the right!
# 

How about using capitalized 'LEFT' to denote icon position ?

``` CSS
.ui.vertical.menu .item > i.icon:not(.LEFT){
    float: right;
    width: 1.22em;
    margin: 0em 0em 0em 0.5em;
}
i.icon.LEFT {
  width: auto;
  margin: 0em 0.5em 0em 0em;
}
i.basic.icon.LEFT {
  width: auto;
  margin: 0em 0.5em 0em 0em;
}
```

[This way](http://jsfiddle.net/r38eh/1/), I was able to have both:

![left right icons attempt 2](https://f.cloud.github.com/assets/4712046/2240552/52790144-9c9a-11e3-8075-909aa7a45a43.PNG)
