### ISSUE TITLE
[Modal] Fullscreen modal stuck to left edge of page

### ISSUE THREAD

**Issue by GammaGames** [Semantic-Org/Semantic-UI#6587]
### Steps
1. Create a fullscreen modal in html
2. Call the modal function on it and show

### Expected Result
Modal should be centered

### Actual Result
Modal is stuck to left edge of page

### Version
2.4.0

### Testcase
https://jsfiddle.net/Ljcyd5ek/

It can be fixed by adding the following css into the page to override it:

```css
.ui.fullscreen.modal {
  left: 2.5% !important;
}
```
