### ISSUE TITLE
[Button] Revealing labeled icon button (feature request)

### ISSUE THREAD

**Issue by GammaGames** [Semantic-Org/Semantic-UI#6624]
### Revealing labeled icon button

I think the ability to have an icon button with an animated label that shows on hover would be a nice feature. I'm not sure if there's a more robust way to do it using js, but I did get an example working with just css:
![peek 2018-10-15 14-51](https://user-images.githubusercontent.com/7832163/46977630-e4a64900-d089-11e8-8a89-d487c8ebdeeb.gif)
The html looks like:
```html
<a class="ui revealing green labeled icon button">
  <i class="check icon"></i> 
  <div class="label">
     Save
  </div>  
</a>
```

The css looks like:
```css
.ui.revealing.labeled.icon.button {
  -webkit-transition: padding 0.4s ease-in-out;
  transition: padding 0.4s ease-in-out;
  transition-delay: 0;
  padding-left: 2.57142857em !important;
  padding-right: 0 !important;
}

.ui.revealing.labeled.icon.button:hover {
  padding-left: 4.07142857em !important;
  padding-right: 1.5em !important;
}

.ui.revealing.button>.label {
  -webkit-transition: max-width 0.4s ease-in-out;
  transition: max-width 0.4s ease-in-out;
  display: inline-block;
  vertical-align: top;
  white-space: nowrap;
  overflow: hidden;
  max-width: 0;
}

.ui.revealing.button:hover>.label {
  max-width: 10em;
}
```

A `max-width` of 10 is reasonable for my examples since I won't have any sentence length button labels.

### Example
https://jsfiddle.net/01zuthmd/
