### ISSUE TITLE
release 2.4.2

### ISSUE THREAD

**Issue by labby** [Semantic-Org/Semantic-UI#6646]
Would be nice if the current released would be tagged and released :-)

**Comment by eroispaziali** [comment]
Yes please! The updated webjar won't be released until this version is tagged.

**Comment by eug48** [comment]
This would be much appreciated - the `semantic-ui-css` package is also out of date with some bugfixes missing and it is a recommended way of using Semantic UI React..

**Comment by eug48** [comment]
Temporary fix for fullscreen modal dialogs not being centered in 2.4.1:

```css
.ui.ui.fullscreen.modal {
    left: unset !important;
}
```
