### ISSUE TITLE
Gulp build outputs invalid CSS.

### ISSUE THREAD

**Issue by sanny-io** [Semantic-Org/Semantic-UI#6746]
### Gulp build outputs invalid CSS.
The `--` in the "Actual Result" area below is a CSS error. There are a couple more areas where those hyphens show up. I've taken a random one as an example.

### Steps
```
npm install semantic-ui --save
cd semantic/
gulp build
```

### Expected Result [(from downloaded zip)](https://github.com/Semantic-Org/Semantic-UI-CSS/archive/master.zip)
```css
.ui.card .image > .ui.ribbon.label,
.ui.image > .ui.ribbon.label {
  left: calc( 0.05rem  -  1.2em );
}
```

### Actual Result (from `gulp build`)
```css
.ui.card .image > .ui.ribbon.label,
.ui.image > .ui.ribbon.label {
  left: calc(--0.05rem - 1.2em);
}
```

### Version
gulp 4.0.0
gulp CLI 2.0.1
npm 6.7.0
Ubuntu 18.04
