### ISSUE TITLE
label margin

### ISSUE THREAD

**Issue by ChrisZhangHD** [Semantic-Org/Semantic-UI#6823]
```
<a href="#" target="_blank" class="ui teal basic left pointing label m-block m-margin-tb-tiny">
                                reading <div class="detail">15</div></a>

.m-margin-tb-tiny {
    margin-top: 0.3em; !important;
    margin-bottom: 0.3em; !important;
}
```
 I used CSS to set 'm-margin-tb-tiny' but the results didn't work, the label had no margin with each other, is there anyone know the reason?

**Comment by marcelodeolive1ra** [comment]
Hi @ChrisZhangHD,

I tried to reproduce your issue, and couldn't reproduce it. As you can see in the image below, the margin was applied (highlighted in orange). If you still have the issue, can you provide more details? If not, let's close this issue :-)

![image](https://user-images.githubusercontent.com/13210266/59299507-2d3af400-8c63-11e9-821b-dbbed95f7612.png)

**Comment by lubber-de** [comment]
@ChrisZhangHD Your CSS is invalid, maybe that's the reason 😉 

Remove the semicolons between the size values and !important
```css
.m-margin-tb-tiny {
    margin-top: 0.3em; !important;
    margin-bottom: 0.3em; !important;
}
```
should become
```css
.m-margin-tb-tiny {
    margin-top: 0.3em !important;
    margin-bottom: 0.3em !important;
}
```
