### ISSUE TITLE
why there is no treeview like plugin?

### ISSUE THREAD

**Issue by dbsxdbsx** [Semantic-Org/Semantic-UI#7048]
for the semantic version 2.4.1. I didn't find an plugin that could behave like a tree view, the most like plugin would be  `Bulleted` list from [here](https://semantic-ui.com/elements/list.html) , but the sub title canot be folded.

Is there some other option?

**Comment by GammaGames** [comment]
Even though this feature is available in SUI, I've been using Fomantic UI since this repo stopped getting updates without issue. They have a bunch of bug fixes and features SUI doesn't have.

Anyway, you should be able to do it with a nested accordion. There's an example in the docs: https://fomantic-ui.com/modules/accordion.html#nested-accordions

If you want to use a non-styled accordion you can add a little css to make the nested menus look better:

```css
.ui.accordion:not(.styled) .title {
  border-bottom: 1px solid grey;
}
.ui.accordion:not(.styled) .content {
  margin-left: 1em;
}
```

[jsfiddle](https://jsfiddle.net/fw6c9Laq/)
