### ISSUE TITLE
Is there a way to allow scrollable component in results from Search module?

### ISSUE THREAD

**Issue by bloodteller123** [Semantic-Org/Semantic-UI#7086]
For example, if the search returns 10 results, instead of displaying all 10 results at the same time, could we allow user to scroll in the results dropdown (initially X are showed) to see the next X +n results?

**Comment by GammaGames** [comment]
I override the results container:

```css
.ui.search .results {
    overflow-y: auto;
    max-height: 70vh;
}
```
