### ISSUE TITLE
[Checkbox] Styles Should Not Adjust Input["text"]

### ISSUE THREAD

**Issue by aviemet** [Semantic-Org/Semantic-UI#792]
Line 12645: 
```css
.ui.checkbox input  {
  position: absolute;
  top: 0px;
  left: 0px;
  opacity: 0;
  outline: none;
}
```

I have a situation where I'd like the user to be able to choose an option with a text input inside. In my local build, I changed the selector to be more specific:
```css
.ui.checkbox input[type="radio"], .ui.checkbox input[type="checkbox"]  {
  position: absolute;
  top: 0px;
  left: 0px;
  opacity: 0;
  outline: none;
}
```

I think this should be changed in the build to allow for this use case.
