### ISSUE TITLE
Form loading with label

### ISSUE THREAD

**Issue by incoder** [Semantic-Org/Semantic-UI#892]
When we use **loading** class on form element, it will not hide labels of input fields.

``` html
<div class="ui form segment loading">
      <div class="field">
        <label>Username</label>
        <div class="ui left labeled icon input">
          <input type="text" placeholder="Username">
          <i class="user icon"></i>
          <div class="ui corner label">
            <i class="icon asterisk"></i>
          </div>
        </div>
      </div>
 </div>
```

Fix for this problem is css z-index

``` css
.ui.form.loading:after{
      z-index: 11;    /* more than 10 */
}
```
